// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/invitee/invitee.proto

package invitee

import (
	context "context"
	fmt "fmt"
	base "github.com/CRORCR/cr-common/proto/base"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetInviteeReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreInviteUserId      string   `protobuf:"bytes,2,opt,name=pre_invite_user_id,json=preInviteUserId,proto3" json:"pre_invite_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInviteeReq) Reset()         { *m = GetInviteeReq{} }
func (m *GetInviteeReq) String() string { return proto.CompactTextString(m) }
func (*GetInviteeReq) ProtoMessage()    {}
func (*GetInviteeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc4badfc659c454, []int{0}
}

func (m *GetInviteeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInviteeReq.Unmarshal(m, b)
}
func (m *GetInviteeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInviteeReq.Marshal(b, m, deterministic)
}
func (m *GetInviteeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInviteeReq.Merge(m, src)
}
func (m *GetInviteeReq) XXX_Size() int {
	return xxx_messageInfo_GetInviteeReq.Size(m)
}
func (m *GetInviteeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInviteeReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetInviteeReq proto.InternalMessageInfo

func (m *GetInviteeReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetInviteeReq) GetPreInviteUserId() string {
	if m != nil {
		return m.PreInviteUserId
	}
	return ""
}

type GetInviteeResp struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreInviteUserId      string   `protobuf:"bytes,2,opt,name=pre_invite_user_id,json=preInviteUserId,proto3" json:"pre_invite_user_id,omitempty"`
	RootUserId           string   `protobuf:"bytes,3,opt,name=root_user_id,json=rootUserId,proto3" json:"root_user_id,omitempty"`
	InviteeInfo          string   `protobuf:"bytes,4,opt,name=invitee_info,json=inviteeInfo,proto3" json:"invitee_info,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetInviteeResp) Reset()         { *m = GetInviteeResp{} }
func (m *GetInviteeResp) String() string { return proto.CompactTextString(m) }
func (*GetInviteeResp) ProtoMessage()    {}
func (*GetInviteeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc4badfc659c454, []int{1}
}

func (m *GetInviteeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetInviteeResp.Unmarshal(m, b)
}
func (m *GetInviteeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetInviteeResp.Marshal(b, m, deterministic)
}
func (m *GetInviteeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetInviteeResp.Merge(m, src)
}
func (m *GetInviteeResp) XXX_Size() int {
	return xxx_messageInfo_GetInviteeResp.Size(m)
}
func (m *GetInviteeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetInviteeResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetInviteeResp proto.InternalMessageInfo

func (m *GetInviteeResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetInviteeResp) GetPreInviteUserId() string {
	if m != nil {
		return m.PreInviteUserId
	}
	return ""
}

func (m *GetInviteeResp) GetRootUserId() string {
	if m != nil {
		return m.RootUserId
	}
	return ""
}

func (m *GetInviteeResp) GetInviteeInfo() string {
	if m != nil {
		return m.InviteeInfo
	}
	return ""
}

func (m *GetInviteeResp) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetInviteeResp) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GetLowerUserResp struct {
	Data                 []*GetLowerUserResp_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination           *base.Pagination         `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetLowerUserResp) Reset()         { *m = GetLowerUserResp{} }
func (m *GetLowerUserResp) String() string { return proto.CompactTextString(m) }
func (*GetLowerUserResp) ProtoMessage()    {}
func (*GetLowerUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc4badfc659c454, []int{2}
}

func (m *GetLowerUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLowerUserResp.Unmarshal(m, b)
}
func (m *GetLowerUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLowerUserResp.Marshal(b, m, deterministic)
}
func (m *GetLowerUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLowerUserResp.Merge(m, src)
}
func (m *GetLowerUserResp) XXX_Size() int {
	return xxx_messageInfo_GetLowerUserResp.Size(m)
}
func (m *GetLowerUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLowerUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetLowerUserResp proto.InternalMessageInfo

func (m *GetLowerUserResp) GetData() []*GetLowerUserResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetLowerUserResp) GetPagination() *base.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetLowerUserResp_Data struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreInviteUserId      string   `protobuf:"bytes,2,opt,name=pre_invite_user_id,json=preInviteUserId,proto3" json:"pre_invite_user_id,omitempty"`
	RootUserId           string   `protobuf:"bytes,3,opt,name=root_user_id,json=rootUserId,proto3" json:"root_user_id,omitempty"`
	InviteeInfo          string   `protobuf:"bytes,4,opt,name=invitee_info,json=inviteeInfo,proto3" json:"invitee_info,omitempty"`
	CreatedAt            string   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLowerUserResp_Data) Reset()         { *m = GetLowerUserResp_Data{} }
func (m *GetLowerUserResp_Data) String() string { return proto.CompactTextString(m) }
func (*GetLowerUserResp_Data) ProtoMessage()    {}
func (*GetLowerUserResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc4badfc659c454, []int{2, 0}
}

func (m *GetLowerUserResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLowerUserResp_Data.Unmarshal(m, b)
}
func (m *GetLowerUserResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLowerUserResp_Data.Marshal(b, m, deterministic)
}
func (m *GetLowerUserResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLowerUserResp_Data.Merge(m, src)
}
func (m *GetLowerUserResp_Data) XXX_Size() int {
	return xxx_messageInfo_GetLowerUserResp_Data.Size(m)
}
func (m *GetLowerUserResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLowerUserResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetLowerUserResp_Data proto.InternalMessageInfo

func (m *GetLowerUserResp_Data) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetLowerUserResp_Data) GetPreInviteUserId() string {
	if m != nil {
		return m.PreInviteUserId
	}
	return ""
}

func (m *GetLowerUserResp_Data) GetRootUserId() string {
	if m != nil {
		return m.RootUserId
	}
	return ""
}

func (m *GetLowerUserResp_Data) GetInviteeInfo() string {
	if m != nil {
		return m.InviteeInfo
	}
	return ""
}

func (m *GetLowerUserResp_Data) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetLowerUserResp_Data) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type SetInviteeReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreInviteUserId      string   `protobuf:"bytes,2,opt,name=pre_invite_user_id,json=preInviteUserId,proto3" json:"pre_invite_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetInviteeReq) Reset()         { *m = SetInviteeReq{} }
func (m *SetInviteeReq) String() string { return proto.CompactTextString(m) }
func (*SetInviteeReq) ProtoMessage()    {}
func (*SetInviteeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc4badfc659c454, []int{3}
}

func (m *SetInviteeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetInviteeReq.Unmarshal(m, b)
}
func (m *SetInviteeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetInviteeReq.Marshal(b, m, deterministic)
}
func (m *SetInviteeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetInviteeReq.Merge(m, src)
}
func (m *SetInviteeReq) XXX_Size() int {
	return xxx_messageInfo_SetInviteeReq.Size(m)
}
func (m *SetInviteeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SetInviteeReq.DiscardUnknown(m)
}

var xxx_messageInfo_SetInviteeReq proto.InternalMessageInfo

func (m *SetInviteeReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *SetInviteeReq) GetPreInviteUserId() string {
	if m != nil {
		return m.PreInviteUserId
	}
	return ""
}

type SetInviteeResp struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetInviteeResp) Reset()         { *m = SetInviteeResp{} }
func (m *SetInviteeResp) String() string { return proto.CompactTextString(m) }
func (*SetInviteeResp) ProtoMessage()    {}
func (*SetInviteeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cdc4badfc659c454, []int{4}
}

func (m *SetInviteeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetInviteeResp.Unmarshal(m, b)
}
func (m *SetInviteeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetInviteeResp.Marshal(b, m, deterministic)
}
func (m *SetInviteeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetInviteeResp.Merge(m, src)
}
func (m *SetInviteeResp) XXX_Size() int {
	return xxx_messageInfo_SetInviteeResp.Size(m)
}
func (m *SetInviteeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SetInviteeResp.DiscardUnknown(m)
}

var xxx_messageInfo_SetInviteeResp proto.InternalMessageInfo

func (m *SetInviteeResp) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *SetInviteeResp) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*GetInviteeReq)(nil), "partner.GetInviteeReq")
	proto.RegisterType((*GetInviteeResp)(nil), "partner.GetInviteeResp")
	proto.RegisterType((*GetLowerUserResp)(nil), "partner.GetLowerUserResp")
	proto.RegisterType((*GetLowerUserResp_Data)(nil), "partner.GetLowerUserResp.Data")
	proto.RegisterType((*SetInviteeReq)(nil), "partner.SetInviteeReq")
	proto.RegisterType((*SetInviteeResp)(nil), "partner.SetInviteeResp")
}

func init() { proto.RegisterFile("proto/invitee/invitee.proto", fileDescriptor_cdc4badfc659c454) }

var fileDescriptor_cdc4badfc659c454 = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x94, 0xc1, 0xce, 0xd2, 0x40,
	0x10, 0xc7, 0x29, 0x20, 0x84, 0xa1, 0x20, 0xd9, 0x44, 0xa9, 0x18, 0x0d, 0xd6, 0x0b, 0x86, 0xd8,
	0x9a, 0xfa, 0x00, 0x06, 0x31, 0x21, 0x4d, 0x34, 0x9a, 0x36, 0x5c, 0xbc, 0x34, 0x4b, 0x3b, 0x60,
	0x0f, 0xed, 0xae, 0xdb, 0x45, 0xdf, 0xd1, 0x8b, 0x5e, 0x7d, 0x1b, 0xd3, 0xed, 0x02, 0x85, 0xc0,
	0xcd, 0xef, 0xf2, 0x5d, 0xa0, 0xfb, 0x9f, 0x5f, 0x7f, 0xed, 0xee, 0x4c, 0x0a, 0x4f, 0xb9, 0x60,
	0x92, 0xb9, 0x69, 0xfe, 0x23, 0x95, 0x88, 0x87, 0x7f, 0x47, 0xa5, 0xa4, 0xcb, 0xa9, 0x90, 0x39,
	0x8a, 0xc9, 0xa3, 0x8a, 0xda, 0xd0, 0x02, 0xd5, 0x4f, 0x55, 0xb7, 0xd7, 0x30, 0x58, 0xa1, 0xf4,
	0xab, 0x7b, 0x02, 0xfc, 0x4e, 0xc6, 0xd0, 0xdd, 0x17, 0x28, 0xa2, 0x34, 0xb1, 0x8c, 0xa9, 0x31,
	0xeb, 0x05, 0x9d, 0x72, 0xe9, 0x27, 0x64, 0x0e, 0x84, 0x0b, 0x8c, 0x2a, 0x7d, 0x74, 0x60, 0x9a,
	0x8a, 0x79, 0xc8, 0x05, 0x56, 0x8e, 0xb5, 0x82, 0xed, 0xbf, 0x06, 0x0c, 0xeb, 0xde, 0x82, 0xff,
	0x1f, 0x31, 0x99, 0x82, 0x29, 0x18, 0x93, 0x47, 0xac, 0xa5, 0x30, 0x28, 0x33, 0x4d, 0xbc, 0x00,
	0x53, 0x1f, 0x41, 0x94, 0xe6, 0x5b, 0x66, 0xb5, 0x15, 0xd1, 0xd7, 0x99, 0x9f, 0x6f, 0x19, 0x79,
	0x06, 0x10, 0x0b, 0xa4, 0x12, 0x93, 0x88, 0x4a, 0xeb, 0x81, 0x02, 0x7a, 0x3a, 0x59, 0xc8, 0xb2,
	0xbc, 0xe7, 0xc9, 0xa1, 0xdc, 0xa9, 0xca, 0x3a, 0x59, 0x48, 0xfb, 0x57, 0x13, 0x46, 0x2b, 0x94,
	0x1f, 0xd9, 0x4f, 0x14, 0xe5, 0x33, 0xd5, 0xee, 0x3c, 0x68, 0x27, 0x54, 0x52, 0xcb, 0x98, 0xb6,
	0x66, 0x7d, 0xef, 0xb9, 0xa3, 0x8f, 0xdd, 0xb9, 0x04, 0x9d, 0x0f, 0x54, 0xd2, 0x40, 0xb1, 0xe4,
	0x0d, 0x00, 0xa7, 0xbb, 0x34, 0xa7, 0x32, 0x65, 0xb9, 0xda, 0x70, 0xdf, 0x1b, 0x39, 0xaa, 0x39,
	0x5f, 0x8e, 0x79, 0x50, 0x63, 0x26, 0xbf, 0x0d, 0x68, 0x97, 0x82, 0xfb, 0x73, 0x98, 0x6b, 0x18,
	0x84, 0x77, 0x30, 0x7f, 0x3e, 0x0c, 0xc3, 0xf3, 0xf1, 0x23, 0xaa, 0x41, 0xa8, 0xa5, 0xea, 0x9a,
	0xbc, 0x84, 0x01, 0x0a, 0xc1, 0x44, 0x94, 0x61, 0x51, 0xd0, 0x1d, 0x6a, 0x9b, 0xa9, 0xc2, 0x4f,
	0x55, 0xe6, 0xfd, 0x31, 0xa0, 0xab, 0x45, 0xe4, 0x1d, 0xc0, 0x69, 0xaa, 0xc9, 0xe3, 0x7a, 0x97,
	0x4f, 0x5b, 0x98, 0x8c, 0xaf, 0xe6, 0x05, 0xb7, 0x1b, 0xa5, 0x20, 0xbc, 0x26, 0x08, 0x6f, 0x08,
	0xc2, 0x4b, 0xc1, 0x12, 0xcc, 0xfa, 0x48, 0xdd, 0x7c, 0x87, 0x27, 0x37, 0x27, 0xd0, 0x6e, 0xbc,
	0x9f, 0x7f, 0x7d, 0xb5, 0x4b, 0xe5, 0xb7, 0xfd, 0xc6, 0x89, 0x59, 0xe6, 0x2e, 0x83, 0xcf, 0xc1,
	0x32, 0x70, 0x63, 0xf1, 0x3a, 0x66, 0x59, 0xc6, 0x72, 0xf7, 0xec, 0x7b, 0xb2, 0xe9, 0xa8, 0xe5,
	0xdb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x9e, 0xbf, 0x7a, 0x67, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InviteeClient is the client API for Invitee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InviteeClient interface {
	GetInvitee(ctx context.Context, in *GetInviteeReq, opts ...grpc.CallOption) (*GetInviteeResp, error)
	SetInvitee(ctx context.Context, in *SetInviteeReq, opts ...grpc.CallOption) (*SetInviteeResp, error)
	GetLowerUser(ctx context.Context, in *GetInviteeReq, opts ...grpc.CallOption) (*GetLowerUserResp, error)
}

type inviteeClient struct {
	cc *grpc.ClientConn
}

func NewInviteeClient(cc *grpc.ClientConn) InviteeClient {
	return &inviteeClient{cc}
}

func (c *inviteeClient) GetInvitee(ctx context.Context, in *GetInviteeReq, opts ...grpc.CallOption) (*GetInviteeResp, error) {
	out := new(GetInviteeResp)
	err := c.cc.Invoke(ctx, "/partner.Invitee/GetInvitee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inviteeClient) SetInvitee(ctx context.Context, in *SetInviteeReq, opts ...grpc.CallOption) (*SetInviteeResp, error) {
	out := new(SetInviteeResp)
	err := c.cc.Invoke(ctx, "/partner.Invitee/SetInvitee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inviteeClient) GetLowerUser(ctx context.Context, in *GetInviteeReq, opts ...grpc.CallOption) (*GetLowerUserResp, error) {
	out := new(GetLowerUserResp)
	err := c.cc.Invoke(ctx, "/partner.Invitee/GetLowerUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InviteeServer is the server API for Invitee service.
type InviteeServer interface {
	GetInvitee(context.Context, *GetInviteeReq) (*GetInviteeResp, error)
	SetInvitee(context.Context, *SetInviteeReq) (*SetInviteeResp, error)
	GetLowerUser(context.Context, *GetInviteeReq) (*GetLowerUserResp, error)
}

// UnimplementedInviteeServer can be embedded to have forward compatible implementations.
type UnimplementedInviteeServer struct {
}

func (*UnimplementedInviteeServer) GetInvitee(ctx context.Context, req *GetInviteeReq) (*GetInviteeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInvitee not implemented")
}
func (*UnimplementedInviteeServer) SetInvitee(ctx context.Context, req *SetInviteeReq) (*SetInviteeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetInvitee not implemented")
}
func (*UnimplementedInviteeServer) GetLowerUser(ctx context.Context, req *GetInviteeReq) (*GetLowerUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLowerUser not implemented")
}

func RegisterInviteeServer(s *grpc.Server, srv InviteeServer) {
	s.RegisterService(&_Invitee_serviceDesc, srv)
}

func _Invitee_GetInvitee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteeServer).GetInvitee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/partner.Invitee/GetInvitee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteeServer).GetInvitee(ctx, req.(*GetInviteeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invitee_SetInvitee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetInviteeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteeServer).SetInvitee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/partner.Invitee/SetInvitee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteeServer).SetInvitee(ctx, req.(*SetInviteeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Invitee_GetLowerUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInviteeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InviteeServer).GetLowerUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/partner.Invitee/GetLowerUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InviteeServer).GetLowerUser(ctx, req.(*GetInviteeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Invitee_serviceDesc = grpc.ServiceDesc{
	ServiceName: "partner.Invitee",
	HandlerType: (*InviteeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInvitee",
			Handler:    _Invitee_GetInvitee_Handler,
		},
		{
			MethodName: "SetInvitee",
			Handler:    _Invitee_SetInvitee_Handler,
		},
		{
			MethodName: "GetLowerUser",
			Handler:    _Invitee_GetLowerUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/invitee/invitee.proto",
}
