// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/his_otc/otc.proto

package his_otc

import (
	context "context"
	fmt "fmt"
	base "github.com/CRORCR/cr-common/proto/base"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetOtcReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status"`
	OrderNo              string   `protobuf:"bytes,3,opt,name=orderNo,proto3" json:"orderNo"`
	StartTime            string   `protobuf:"bytes,4,opt,name=startTime,proto3" json:"startTime"`
	EndTime              string   `protobuf:"bytes,5,opt,name=endTime,proto3" json:"endTime"`
	Page                 int32    `protobuf:"varint,6,opt,name=Page,proto3" json:"Page"`
	Size                 int32    `protobuf:"varint,7,opt,name=Size,proto3" json:"Size"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOtcReq) Reset()         { *m = GetOtcReq{} }
func (m *GetOtcReq) String() string { return proto.CompactTextString(m) }
func (*GetOtcReq) ProtoMessage()    {}
func (*GetOtcReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef28ce1e566e990, []int{0}
}

func (m *GetOtcReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOtcReq.Unmarshal(m, b)
}
func (m *GetOtcReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOtcReq.Marshal(b, m, deterministic)
}
func (m *GetOtcReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOtcReq.Merge(m, src)
}
func (m *GetOtcReq) XXX_Size() int {
	return xxx_messageInfo_GetOtcReq.Size(m)
}
func (m *GetOtcReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOtcReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOtcReq proto.InternalMessageInfo

func (m *GetOtcReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetOtcReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetOtcReq) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *GetOtcReq) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetOtcReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *GetOtcReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetOtcReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetNormalOtcResp struct {
	Status               int32                    `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg                  string                   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	Data                 []*GetNormalOtcResp_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
	Pag                  *base.Pagination         `protobuf:"bytes,4,opt,name=pag,proto3" json:"pag"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *GetNormalOtcResp) Reset()         { *m = GetNormalOtcResp{} }
func (m *GetNormalOtcResp) String() string { return proto.CompactTextString(m) }
func (*GetNormalOtcResp) ProtoMessage()    {}
func (*GetNormalOtcResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef28ce1e566e990, []int{1}
}

func (m *GetNormalOtcResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNormalOtcResp.Unmarshal(m, b)
}
func (m *GetNormalOtcResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNormalOtcResp.Marshal(b, m, deterministic)
}
func (m *GetNormalOtcResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNormalOtcResp.Merge(m, src)
}
func (m *GetNormalOtcResp) XXX_Size() int {
	return xxx_messageInfo_GetNormalOtcResp.Size(m)
}
func (m *GetNormalOtcResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNormalOtcResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetNormalOtcResp proto.InternalMessageInfo

func (m *GetNormalOtcResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetNormalOtcResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetNormalOtcResp) GetData() []*GetNormalOtcResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetNormalOtcResp) GetPag() *base.Pagination {
	if m != nil {
		return m.Pag
	}
	return nil
}

type GetNormalOtcResp_Data struct {
	ServiceType          string   `protobuf:"bytes,1,opt,name=service_type,json=serviceType,proto3" json:"service_type"`
	PreloadNo            string   `protobuf:"bytes,2,opt,name=preload_no,json=preloadNo,proto3" json:"preload_no"`
	BillNo               string   `protobuf:"bytes,3,opt,name=billNo,proto3" json:"billNo"`
	Currency             string   `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency"`
	Amount               string   `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount"`
	UniMember            string   `protobuf:"bytes,6,opt,name=uniMember,proto3" json:"uuid"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status"`
	CreateAt             string   `protobuf:"bytes,8,opt,name=createAt,proto3" json:"createAt"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNormalOtcResp_Data) Reset()         { *m = GetNormalOtcResp_Data{} }
func (m *GetNormalOtcResp_Data) String() string { return proto.CompactTextString(m) }
func (*GetNormalOtcResp_Data) ProtoMessage()    {}
func (*GetNormalOtcResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef28ce1e566e990, []int{1, 0}
}

func (m *GetNormalOtcResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNormalOtcResp_Data.Unmarshal(m, b)
}
func (m *GetNormalOtcResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNormalOtcResp_Data.Marshal(b, m, deterministic)
}
func (m *GetNormalOtcResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNormalOtcResp_Data.Merge(m, src)
}
func (m *GetNormalOtcResp_Data) XXX_Size() int {
	return xxx_messageInfo_GetNormalOtcResp_Data.Size(m)
}
func (m *GetNormalOtcResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNormalOtcResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetNormalOtcResp_Data proto.InternalMessageInfo

func (m *GetNormalOtcResp_Data) GetServiceType() string {
	if m != nil {
		return m.ServiceType
	}
	return ""
}

func (m *GetNormalOtcResp_Data) GetPreloadNo() string {
	if m != nil {
		return m.PreloadNo
	}
	return ""
}

func (m *GetNormalOtcResp_Data) GetBillNo() string {
	if m != nil {
		return m.BillNo
	}
	return ""
}

func (m *GetNormalOtcResp_Data) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetNormalOtcResp_Data) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *GetNormalOtcResp_Data) GetUniMember() string {
	if m != nil {
		return m.UniMember
	}
	return ""
}

func (m *GetNormalOtcResp_Data) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetNormalOtcResp_Data) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

type GetUsdtOtcResp struct {
	Status               int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg                  string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	Data                 []*GetUsdtOtcResp_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
	Pag                  *base.Pagination       `protobuf:"bytes,4,opt,name=pag,proto3" json:"pag"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetUsdtOtcResp) Reset()         { *m = GetUsdtOtcResp{} }
func (m *GetUsdtOtcResp) String() string { return proto.CompactTextString(m) }
func (*GetUsdtOtcResp) ProtoMessage()    {}
func (*GetUsdtOtcResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef28ce1e566e990, []int{2}
}

func (m *GetUsdtOtcResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsdtOtcResp.Unmarshal(m, b)
}
func (m *GetUsdtOtcResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsdtOtcResp.Marshal(b, m, deterministic)
}
func (m *GetUsdtOtcResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsdtOtcResp.Merge(m, src)
}
func (m *GetUsdtOtcResp) XXX_Size() int {
	return xxx_messageInfo_GetUsdtOtcResp.Size(m)
}
func (m *GetUsdtOtcResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsdtOtcResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsdtOtcResp proto.InternalMessageInfo

func (m *GetUsdtOtcResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetUsdtOtcResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetUsdtOtcResp) GetData() []*GetUsdtOtcResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUsdtOtcResp) GetPag() *base.Pagination {
	if m != nil {
		return m.Pag
	}
	return nil
}

type GetUsdtOtcResp_Data struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	OrderNo              string   `protobuf:"bytes,2,opt,name=orderNo,proto3" json:"orderNo"`
	Currency             string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency"`
	Type                 int32    `protobuf:"varint,4,opt,name=type,proto3" json:"type"`
	Status               int32    `protobuf:"varint,5,opt,name=status,proto3" json:"status"`
	Tid                  int32    `protobuf:"varint,6,opt,name=tid,proto3" json:"tid"`
	UserName             string   `protobuf:"bytes,7,opt,name=userName,proto3" json:"userName"`
	CardId               string   `protobuf:"bytes,8,opt,name=cardId,proto3" json:"cardId"`
	InitialMoney         string   `protobuf:"bytes,9,opt,name=initialMoney,proto3" json:"initialMoney"`
	RealMoney            string   `protobuf:"bytes,10,opt,name=realMoney,proto3" json:"realMoney"`
	OtcAmount            string   `protobuf:"bytes,11,opt,name=otcAmount,proto3" json:"otcAmount"`
	OtcRealAmount        string   `protobuf:"bytes,12,opt,name=otcRealAmount,proto3" json:"otcRealAmount"`
	InitialAmount        string   `protobuf:"bytes,13,opt,name=initialAmount,proto3" json:"initialAmount"`
	RealAmount           string   `protobuf:"bytes,14,opt,name=realAmount,proto3" json:"realAmount"`
	InitialUnitPrice     string   `protobuf:"bytes,15,opt,name=initialUnitPrice,proto3" json:"initialUnitPrice"`
	MarkupUnitPrice      string   `protobuf:"bytes,16,opt,name=markupUnitPrice,proto3" json:"markupUnitPrice"`
	Fee                  string   `protobuf:"bytes,17,opt,name=fee,proto3" json:"fee"`
	FeeRate              string   `protobuf:"bytes,18,opt,name=feeRate,proto3" json:"feeRate"`
	OtcFee               string   `protobuf:"bytes,19,opt,name=otcFee,proto3" json:"otcFee"`
	OtcFeeRate           string   `protobuf:"bytes,20,opt,name=otcFeeRate,proto3" json:"otcFeeRate"`
	ProfitAmount         string   `protobuf:"bytes,21,opt,name=profitAmount,proto3" json:"profitAmount"`
	CreatedAt            string   `protobuf:"bytes,22,opt,name=createdAt,proto3" json:"createdAt"`
	UpdatedAt            string   `protobuf:"bytes,23,opt,name=updatedAt,proto3" json:"updatedAt"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsdtOtcResp_Data) Reset()         { *m = GetUsdtOtcResp_Data{} }
func (m *GetUsdtOtcResp_Data) String() string { return proto.CompactTextString(m) }
func (*GetUsdtOtcResp_Data) ProtoMessage()    {}
func (*GetUsdtOtcResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ef28ce1e566e990, []int{2, 0}
}

func (m *GetUsdtOtcResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsdtOtcResp_Data.Unmarshal(m, b)
}
func (m *GetUsdtOtcResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsdtOtcResp_Data.Marshal(b, m, deterministic)
}
func (m *GetUsdtOtcResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsdtOtcResp_Data.Merge(m, src)
}
func (m *GetUsdtOtcResp_Data) XXX_Size() int {
	return xxx_messageInfo_GetUsdtOtcResp_Data.Size(m)
}
func (m *GetUsdtOtcResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsdtOtcResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsdtOtcResp_Data proto.InternalMessageInfo

func (m *GetUsdtOtcResp_Data) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetOrderNo() string {
	if m != nil {
		return m.OrderNo
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *GetUsdtOtcResp_Data) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetUsdtOtcResp_Data) GetTid() int32 {
	if m != nil {
		return m.Tid
	}
	return 0
}

func (m *GetUsdtOtcResp_Data) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetCardId() string {
	if m != nil {
		return m.CardId
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetInitialMoney() string {
	if m != nil {
		return m.InitialMoney
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetRealMoney() string {
	if m != nil {
		return m.RealMoney
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetOtcAmount() string {
	if m != nil {
		return m.OtcAmount
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetOtcRealAmount() string {
	if m != nil {
		return m.OtcRealAmount
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetInitialAmount() string {
	if m != nil {
		return m.InitialAmount
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetRealAmount() string {
	if m != nil {
		return m.RealAmount
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetInitialUnitPrice() string {
	if m != nil {
		return m.InitialUnitPrice
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetMarkupUnitPrice() string {
	if m != nil {
		return m.MarkupUnitPrice
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetFee() string {
	if m != nil {
		return m.Fee
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetFeeRate() string {
	if m != nil {
		return m.FeeRate
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetOtcFee() string {
	if m != nil {
		return m.OtcFee
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetOtcFeeRate() string {
	if m != nil {
		return m.OtcFeeRate
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetProfitAmount() string {
	if m != nil {
		return m.ProfitAmount
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetUsdtOtcResp_Data) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*GetOtcReq)(nil), "his_otc.GetOtcReq")
	proto.RegisterType((*GetNormalOtcResp)(nil), "his_otc.GetNormalOtcResp")
	proto.RegisterType((*GetNormalOtcResp_Data)(nil), "his_otc.GetNormalOtcResp.Data")
	proto.RegisterType((*GetUsdtOtcResp)(nil), "his_otc.GetUsdtOtcResp")
	proto.RegisterType((*GetUsdtOtcResp_Data)(nil), "his_otc.GetUsdtOtcResp.Data")
}

func init() { proto.RegisterFile("proto/his_otc/otc.proto", fileDescriptor_6ef28ce1e566e990) }

var fileDescriptor_6ef28ce1e566e990 = []byte{
	// 732 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcb, 0x6e, 0x13, 0x4b,
	0x10, 0x8d, 0xe3, 0x57, 0xdc, 0xce, 0xc3, 0xb7, 0xef, 0x4d, 0xd2, 0xd7, 0x0a, 0x51, 0xb0, 0x58,
	0x18, 0x10, 0x36, 0x32, 0x7b, 0xa4, 0x24, 0x08, 0x07, 0x89, 0x38, 0xd1, 0x90, 0x6c, 0xd8, 0x44,
	0xed, 0x9e, 0xb2, 0xd3, 0xc2, 0x33, 0x3d, 0xf4, 0xd4, 0x20, 0x99, 0xaf, 0xe0, 0x33, 0xd8, 0xb2,
	0xe6, 0x7f, 0xf8, 0x0b, 0x24, 0xd4, 0x0f, 0xdb, 0x63, 0x93, 0x2c, 0xb2, 0xb1, 0xaa, 0x4e, 0x9d,
	0xae, 0xa9, 0x3e, 0x55, 0xd5, 0x26, 0xfb, 0x89, 0x56, 0xa8, 0xba, 0xb7, 0x32, 0xbd, 0x51, 0x28,
	0xba, 0x0a, 0x45, 0xc7, 0x22, 0xb4, 0xea, 0xa1, 0xe6, 0xae, 0x63, 0x0c, 0x79, 0x0a, 0xf6, 0xc7,
	0xc5, 0x5b, 0x3f, 0x0a, 0xa4, 0xd6, 0x07, 0xbc, 0x40, 0x11, 0xc0, 0x67, 0x4a, 0x49, 0x29, 0xcb,
	0x64, 0xc8, 0x0a, 0x47, 0x85, 0x76, 0x2d, 0xb0, 0x36, 0xdd, 0x23, 0x95, 0x14, 0x39, 0x66, 0x29,
	0x5b, 0xb7, 0xa8, 0xf7, 0x28, 0x23, 0x55, 0xa5, 0x43, 0xd0, 0x03, 0xc5, 0x8a, 0x36, 0x30, 0x73,
	0xe9, 0x01, 0xa9, 0xa5, 0xc8, 0x35, 0x5e, 0xc9, 0x08, 0x58, 0xc9, 0xc6, 0x16, 0x80, 0x39, 0x07,
	0x71, 0x68, 0x63, 0x65, 0x77, 0xce, 0xbb, 0xe6, 0xeb, 0x97, 0x7c, 0x0c, 0xac, 0x72, 0x54, 0x68,
	0x97, 0x03, 0x6b, 0x1b, 0xec, 0x83, 0xfc, 0x0a, 0xac, 0xea, 0x30, 0x63, 0xb7, 0x7e, 0xaf, 0x93,
	0x46, 0x1f, 0x70, 0xa0, 0x74, 0xc4, 0x27, 0xb6, 0xf2, 0x34, 0xc9, 0x95, 0x59, 0xb0, 0xd4, 0x59,
	0x99, 0x0d, 0x52, 0x8c, 0xd2, 0xb1, 0xaf, 0xdd, 0x98, 0xb4, 0x47, 0x4a, 0x21, 0x47, 0xce, 0x8a,
	0x47, 0xc5, 0x76, 0xbd, 0x77, 0xd8, 0xf1, 0x0a, 0x75, 0x56, 0x53, 0x76, 0xde, 0x70, 0xe4, 0x81,
	0xe5, 0xd2, 0x16, 0x29, 0x26, 0x7c, 0x6c, 0x2f, 0x53, 0xef, 0x35, 0x3a, 0x56, 0xc0, 0x4b, 0x3e,
	0x96, 0x31, 0x47, 0xa9, 0xe2, 0xc0, 0x04, 0x9b, 0xbf, 0x0a, 0xa4, 0x64, 0x8e, 0xd0, 0xc7, 0x64,
	0x33, 0x05, 0xfd, 0x45, 0x0a, 0xb8, 0xc1, 0x69, 0x02, 0x5e, 0xcd, 0xba, 0xc7, 0xae, 0xa6, 0x09,
	0xd0, 0x47, 0x84, 0x24, 0x1a, 0x26, 0x8a, 0x87, 0x37, 0xb1, 0xf2, 0xc5, 0xd5, 0x3c, 0x32, 0x50,
	0xe6, 0x32, 0x43, 0x39, 0x99, 0xcc, 0xa5, 0xf5, 0x1e, 0x6d, 0x92, 0x0d, 0x91, 0x69, 0x0d, 0xb1,
	0x98, 0x7a, 0x61, 0xe7, 0xbe, 0x39, 0xc3, 0x23, 0x95, 0xc5, 0xe8, 0x65, 0xf5, 0x9e, 0xe9, 0x46,
	0x16, 0xcb, 0x73, 0x88, 0x86, 0xa0, 0xad, 0xb4, 0xb5, 0x60, 0x01, 0xe4, 0x64, 0xab, 0x2e, 0xc9,
	0x66, 0xbe, 0xa4, 0x81, 0x23, 0x1c, 0x23, 0xdb, 0xf0, 0x5f, 0xf2, 0x7e, 0xeb, 0x67, 0x85, 0x6c,
	0xf7, 0x01, 0xaf, 0xd3, 0x10, 0x1f, 0xae, 0xfe, 0xcb, 0x25, 0xf5, 0x0f, 0xf2, 0xea, 0xe7, 0x12,
	0x3e, 0x54, 0xfb, 0xef, 0x65, 0xaf, 0xfd, 0x5d, 0x13, 0x9c, 0x9b, 0xd4, 0xf5, 0xe5, 0x49, 0xcd,
	0xeb, 0x59, 0x5c, 0xd1, 0x93, 0x92, 0x92, 0xed, 0x5e, 0xc9, 0x4d, 0x9e, 0xb1, 0x73, 0xd7, 0x2c,
	0xaf, 0x5e, 0x13, 0x65, 0xe8, 0x07, 0xd7, 0x98, 0x26, 0x73, 0x96, 0x82, 0x1e, 0xf0, 0xc8, 0xcd,
	0x6e, 0x2d, 0x98, 0xfb, 0x26, 0x8b, 0xe0, 0x3a, 0x7c, 0x17, 0x7a, 0x65, 0xbd, 0x47, 0x5b, 0x64,
	0x53, 0xc6, 0x12, 0x25, 0x9f, 0x9c, 0xab, 0x18, 0xa6, 0xac, 0x66, 0xa3, 0x4b, 0x98, 0xe9, 0xa6,
	0x86, 0x19, 0x81, 0xb8, 0x6e, 0xce, 0x01, 0x13, 0x55, 0x28, 0x8e, 0xdd, 0x18, 0xd4, 0x5d, 0x74,
	0x0e, 0xd0, 0x27, 0x64, 0x4b, 0x19, 0x79, 0xf9, 0xc4, 0x33, 0x36, 0x2d, 0x63, 0x19, 0x34, 0x2c,
	0xff, 0x45, 0xcf, 0xda, 0x72, 0xac, 0x25, 0x90, 0x1e, 0x12, 0xa2, 0x17, 0x89, 0xb6, 0x2d, 0x25,
	0x87, 0xd0, 0x67, 0xa4, 0xe1, 0x0f, 0x5c, 0xc7, 0x12, 0x2f, 0xb5, 0x14, 0xc0, 0x76, 0x2c, 0xeb,
	0x2f, 0x9c, 0xb6, 0xc9, 0x4e, 0xc4, 0xf5, 0xa7, 0x2c, 0x59, 0x50, 0x1b, 0x96, 0xba, 0x0a, 0x1b,
	0x9d, 0x47, 0x00, 0xec, 0x1f, 0x37, 0x4e, 0x23, 0xb0, 0xaf, 0xc9, 0x08, 0x20, 0xe0, 0x08, 0x8c,
	0xba, 0xde, 0x7a, 0xd7, 0xa8, 0xac, 0x50, 0xbc, 0x05, 0x60, 0xff, 0x3a, 0x95, 0x9d, 0x67, 0x2a,
	0x77, 0x96, 0x3d, 0xf4, 0x9f, 0xab, 0x7c, 0x81, 0x98, 0x2e, 0x24, 0x5a, 0x8d, 0x24, 0xfa, 0xbb,
	0xed, 0xba, 0x2e, 0xe4, 0x31, 0xa3, 0xb3, 0xdb, 0x86, 0xf0, 0x18, 0xd9, 0x9e, 0xd3, 0x79, 0x0e,
	0xd8, 0x8d, 0x4b, 0x42, 0x1f, 0xdd, 0xf7, 0x1b, 0x37, 0x03, 0x7a, 0xdf, 0x0a, 0x84, 0x9c, 0xc9,
	0xf4, 0x02, 0xc5, 0x7b, 0x99, 0x22, 0x3d, 0x21, 0x3b, 0x7d, 0xc0, 0x33, 0x99, 0xce, 0xdf, 0x1e,
	0x4a, 0xf3, 0x4b, 0xe1, 0x5e, 0xe6, 0xe6, 0xff, 0xf7, 0x3e, 0x53, 0xad, 0x35, 0xfa, 0x9a, 0x6c,
	0xb9, 0x1c, 0x7e, 0x83, 0xee, 0xcc, 0xb0, 0x7f, 0xcf, 0xaa, 0xb5, 0xd6, 0x4e, 0x9e, 0x7f, 0x7c,
	0x3a, 0x96, 0x78, 0x9b, 0x0d, 0x3b, 0x42, 0x45, 0xdd, 0xd3, 0xe0, 0x22, 0x38, 0x0d, 0xba, 0x42,
	0xbf, 0x10, 0x2a, 0x8a, 0x54, 0xdc, 0x5d, 0xfa, 0x6f, 0x19, 0x56, 0xac, 0xfb, 0xea, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa9, 0xfc, 0x0d, 0x7d, 0x73, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HisOtcListClient is the client API for HisOtcList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HisOtcListClient interface {
	GetHisNormalOtc(ctx context.Context, in *GetOtcReq, opts ...grpc.CallOption) (*GetNormalOtcResp, error)
	GetHisUsdtOtc(ctx context.Context, in *GetOtcReq, opts ...grpc.CallOption) (*GetUsdtOtcResp, error)
}

type hisOtcListClient struct {
	cc *grpc.ClientConn
}

func NewHisOtcListClient(cc *grpc.ClientConn) HisOtcListClient {
	return &hisOtcListClient{cc}
}

func (c *hisOtcListClient) GetHisNormalOtc(ctx context.Context, in *GetOtcReq, opts ...grpc.CallOption) (*GetNormalOtcResp, error) {
	out := new(GetNormalOtcResp)
	err := c.cc.Invoke(ctx, "/his_otc.HisOtcList/GetHisNormalOtc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hisOtcListClient) GetHisUsdtOtc(ctx context.Context, in *GetOtcReq, opts ...grpc.CallOption) (*GetUsdtOtcResp, error) {
	out := new(GetUsdtOtcResp)
	err := c.cc.Invoke(ctx, "/his_otc.HisOtcList/GetHisUsdtOtc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HisOtcListServer is the server API for HisOtcList service.
type HisOtcListServer interface {
	GetHisNormalOtc(context.Context, *GetOtcReq) (*GetNormalOtcResp, error)
	GetHisUsdtOtc(context.Context, *GetOtcReq) (*GetUsdtOtcResp, error)
}

// UnimplementedHisOtcListServer can be embedded to have forward compatible implementations.
type UnimplementedHisOtcListServer struct {
}

func (*UnimplementedHisOtcListServer) GetHisNormalOtc(ctx context.Context, req *GetOtcReq) (*GetNormalOtcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHisNormalOtc not implemented")
}
func (*UnimplementedHisOtcListServer) GetHisUsdtOtc(ctx context.Context, req *GetOtcReq) (*GetUsdtOtcResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHisUsdtOtc not implemented")
}

func RegisterHisOtcListServer(s *grpc.Server, srv HisOtcListServer) {
	s.RegisterService(&_HisOtcList_serviceDesc, srv)
}

func _HisOtcList_GetHisNormalOtc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOtcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HisOtcListServer).GetHisNormalOtc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/his_otc.HisOtcList/GetHisNormalOtc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HisOtcListServer).GetHisNormalOtc(ctx, req.(*GetOtcReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HisOtcList_GetHisUsdtOtc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOtcReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HisOtcListServer).GetHisUsdtOtc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/his_otc.HisOtcList/GetHisUsdtOtc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HisOtcListServer).GetHisUsdtOtc(ctx, req.(*GetOtcReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _HisOtcList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "his_otc.HisOtcList",
	HandlerType: (*HisOtcListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHisNormalOtc",
			Handler:    _HisOtcList_GetHisNormalOtc_Handler,
		},
		{
			MethodName: "GetHisUsdtOtc",
			Handler:    _HisOtcList_GetHisUsdtOtc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/his_otc/otc.proto",
}
