// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/his_transfer/his_transfer.proto

package his_transfer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetHisTransferReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Direction            string   `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Page                 string   `protobuf:"bytes,6,opt,name=page,proto3" json:"page,omitempty"`
	Size                 string   `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHisTransferReq) Reset()         { *m = GetHisTransferReq{} }
func (m *GetHisTransferReq) String() string { return proto.CompactTextString(m) }
func (*GetHisTransferReq) ProtoMessage()    {}
func (*GetHisTransferReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_491afa8a17bc335d, []int{0}
}

func (m *GetHisTransferReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHisTransferReq.Unmarshal(m, b)
}
func (m *GetHisTransferReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHisTransferReq.Marshal(b, m, deterministic)
}
func (m *GetHisTransferReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHisTransferReq.Merge(m, src)
}
func (m *GetHisTransferReq) XXX_Size() int {
	return xxx_messageInfo_GetHisTransferReq.Size(m)
}
func (m *GetHisTransferReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHisTransferReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetHisTransferReq proto.InternalMessageInfo

func (m *GetHisTransferReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetHisTransferReq) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *GetHisTransferReq) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *GetHisTransferReq) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetHisTransferReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *GetHisTransferReq) GetPage() string {
	if m != nil {
		return m.Page
	}
	return ""
}

func (m *GetHisTransferReq) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

type GetHisTransferReq_Data struct {
	TotalRecord          int32    `protobuf:"varint,1,opt,name=totalRecord,proto3" json:"totalRecord,omitempty"`
	CurrentPage          int32    `protobuf:"varint,2,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TotalPages           int32    `protobuf:"varint,4,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	HasNext              bool     `protobuf:"varint,5,opt,name=hasNext,proto3" json:"hasNext,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHisTransferReq_Data) Reset()         { *m = GetHisTransferReq_Data{} }
func (m *GetHisTransferReq_Data) String() string { return proto.CompactTextString(m) }
func (*GetHisTransferReq_Data) ProtoMessage()    {}
func (*GetHisTransferReq_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_491afa8a17bc335d, []int{0, 0}
}

func (m *GetHisTransferReq_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHisTransferReq_Data.Unmarshal(m, b)
}
func (m *GetHisTransferReq_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHisTransferReq_Data.Marshal(b, m, deterministic)
}
func (m *GetHisTransferReq_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHisTransferReq_Data.Merge(m, src)
}
func (m *GetHisTransferReq_Data) XXX_Size() int {
	return xxx_messageInfo_GetHisTransferReq_Data.Size(m)
}
func (m *GetHisTransferReq_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHisTransferReq_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetHisTransferReq_Data proto.InternalMessageInfo

func (m *GetHisTransferReq_Data) GetTotalRecord() int32 {
	if m != nil {
		return m.TotalRecord
	}
	return 0
}

func (m *GetHisTransferReq_Data) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *GetHisTransferReq_Data) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *GetHisTransferReq_Data) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *GetHisTransferReq_Data) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

type GetHisTransferResp struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Direction            string   `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	Amount               string   `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Remark               string   `protobuf:"bytes,7,opt,name=remark,proto3" json:"remark,omitempty"`
	Reason               string   `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	Status               string   `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt            string   `protobuf:"bytes,10,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHisTransferResp) Reset()         { *m = GetHisTransferResp{} }
func (m *GetHisTransferResp) String() string { return proto.CompactTextString(m) }
func (*GetHisTransferResp) ProtoMessage()    {}
func (*GetHisTransferResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_491afa8a17bc335d, []int{1}
}

func (m *GetHisTransferResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHisTransferResp.Unmarshal(m, b)
}
func (m *GetHisTransferResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHisTransferResp.Marshal(b, m, deterministic)
}
func (m *GetHisTransferResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHisTransferResp.Merge(m, src)
}
func (m *GetHisTransferResp) XXX_Size() int {
	return xxx_messageInfo_GetHisTransferResp.Size(m)
}
func (m *GetHisTransferResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHisTransferResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetHisTransferResp proto.InternalMessageInfo

func (m *GetHisTransferResp) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetHisTransferResp) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *GetHisTransferResp) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetHisTransferResp) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetHisTransferResp) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *GetHisTransferResp) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *GetHisTransferResp) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *GetHisTransferResp) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *GetHisTransferResp) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetHisTransferResp) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*GetHisTransferReq)(nil), "his_transfer.GetHisTransferReq")
	proto.RegisterType((*GetHisTransferReq_Data)(nil), "his_transfer.GetHisTransferReq.Data")
	proto.RegisterType((*GetHisTransferResp)(nil), "his_transfer.GetHisTransferResp")
}

func init() {
	proto.RegisterFile("proto/his_transfer/his_transfer.proto", fileDescriptor_491afa8a17bc335d)
}

var fileDescriptor_491afa8a17bc335d = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xd1, 0x8a, 0xd4, 0x30,
	0x14, 0x86, 0x9d, 0xee, 0x74, 0xb6, 0x73, 0x56, 0x04, 0x73, 0x21, 0xa1, 0x88, 0x0e, 0x03, 0x82,
	0x37, 0xb6, 0xa2, 0x4f, 0xa0, 0x2b, 0xe8, 0xd5, 0x2a, 0x71, 0xbd, 0xf1, 0x46, 0xb2, 0x69, 0x76,
	0x27, 0x38, 0x6d, 0x6a, 0x72, 0x0a, 0xae, 0x4f, 0xe1, 0x23, 0xf8, 0x70, 0x3e, 0x88, 0x9c, 0xa4,
	0xad, 0xed, 0x0c, 0x08, 0xde, 0xe5, 0xff, 0xfe, 0x43, 0xce, 0x39, 0x7f, 0x53, 0x78, 0xd2, 0x3a,
	0x8b, 0xb6, 0xdc, 0x19, 0xff, 0x05, 0x9d, 0x6c, 0xfc, 0xb5, 0x76, 0x33, 0x51, 0x04, 0x9f, 0xdd,
	0x9d, 0xb2, 0xed, 0xef, 0x04, 0xee, 0xbf, 0xd5, 0xf8, 0xce, 0xf8, 0xcb, 0x1e, 0x09, 0xfd, 0x8d,
	0x31, 0x58, 0x76, 0x9d, 0xa9, 0xf8, 0x62, 0xb3, 0x78, 0xba, 0x16, 0xe1, 0xcc, 0x72, 0xc8, 0xae,
	0xbb, 0xfd, 0xfe, 0x42, 0xd6, 0x9a, 0x27, 0x81, 0x8f, 0x9a, 0x3d, 0x84, 0x75, 0x65, 0x9c, 0x56,
	0x68, 0x6c, 0xc3, 0x4f, 0x82, 0xf9, 0x17, 0x90, 0xeb, 0x51, 0x3a, 0xbc, 0x34, 0xb5, 0xe6, 0xcb,
	0xe8, 0x8e, 0x80, 0x71, 0x38, 0xd5, 0x4d, 0x15, 0xbc, 0x34, 0x78, 0x83, 0xa4, 0x29, 0x5a, 0x79,
	0xa3, 0xf9, 0x2a, 0x4e, 0x41, 0x67, 0x62, 0xde, 0xfc, 0xd0, 0xfc, 0x34, 0x32, 0x3a, 0xe7, 0xbf,
	0x16, 0xb0, 0x7c, 0x23, 0x51, 0xb2, 0x0d, 0x9c, 0xa1, 0x45, 0xb9, 0x17, 0x5a, 0x59, 0x17, 0xa7,
	0x4f, 0xc5, 0x14, 0x51, 0x85, 0xea, 0x9c, 0xd3, 0x0d, 0x7e, 0xa0, 0x9b, 0x93, 0x58, 0x31, 0x41,
	0xb4, 0x26, 0x35, 0xfa, 0x48, 0x4d, 0x4e, 0x82, 0x3d, 0x6a, 0xf6, 0x08, 0x20, 0x5c, 0x46, 0x85,
	0x3e, 0x6c, 0x92, 0x8a, 0x09, 0xa1, 0x55, 0x76, 0xd2, 0x5f, 0xe8, 0xef, 0x18, 0x56, 0xc9, 0xc4,
	0x20, 0xb7, 0x3f, 0x13, 0x60, 0x87, 0x31, 0xfb, 0xf6, 0xbf, 0x73, 0xce, 0x21, 0x8b, 0xb3, 0xaa,
	0xdb, 0x3e, 0xe6, 0x51, 0xd3, 0x5d, 0x78, 0xdb, 0x0e, 0x01, 0x87, 0xf3, 0xfc, 0xbb, 0xa4, 0x87,
	0xdf, 0xe5, 0x01, 0xac, 0x64, 0x6d, 0xbb, 0x06, 0xfb, 0x84, 0x7b, 0x45, 0xdc, 0xe9, 0x5a, 0xba,
	0xaf, 0x7d, 0xca, 0xbd, 0x8a, 0x5c, 0x7a, 0xdb, 0xf0, 0x6c, 0xe0, 0xa4, 0x88, 0x7b, 0x94, 0xd8,
	0x79, 0xbe, 0x8e, 0x3c, 0x2a, 0xea, 0xae, 0x9c, 0x96, 0xa8, 0xab, 0x57, 0xc8, 0x21, 0x76, 0x1f,
	0xc1, 0x8b, 0x0a, 0xce, 0x26, 0x71, 0xb0, 0x4f, 0x70, 0x6f, 0x1e, 0x10, 0x7b, 0x5c, 0xcc, 0x5e,
	0xef, 0xd1, 0x2b, 0xcd, 0x37, 0xff, 0x2e, 0xf0, 0xed, 0xf6, 0xce, 0xeb, 0xe7, 0x9f, 0x8b, 0x1b,
	0x83, 0xbb, 0xee, 0xaa, 0x50, 0xb6, 0x2e, 0xcf, 0xc5, 0x7b, 0x71, 0x2e, 0x4a, 0xe5, 0x9e, 0x29,
	0x5b, 0xd7, 0xb6, 0x29, 0x8f, 0x7f, 0x99, 0xab, 0x55, 0x60, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xf1, 0xcf, 0xeb, 0xf7, 0x4f, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HisTransferClient is the client API for HisTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HisTransferClient interface {
	GetHisTransfer(ctx context.Context, in *GetHisTransferReq, opts ...grpc.CallOption) (*GetHisTransferResp, error)
}

type hisTransferClient struct {
	cc *grpc.ClientConn
}

func NewHisTransferClient(cc *grpc.ClientConn) HisTransferClient {
	return &hisTransferClient{cc}
}

func (c *hisTransferClient) GetHisTransfer(ctx context.Context, in *GetHisTransferReq, opts ...grpc.CallOption) (*GetHisTransferResp, error) {
	out := new(GetHisTransferResp)
	err := c.cc.Invoke(ctx, "/his_transfer.HisTransfer/GetHisTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HisTransferServer is the server API for HisTransfer service.
type HisTransferServer interface {
	GetHisTransfer(context.Context, *GetHisTransferReq) (*GetHisTransferResp, error)
}

// UnimplementedHisTransferServer can be embedded to have forward compatible implementations.
type UnimplementedHisTransferServer struct {
}

func (*UnimplementedHisTransferServer) GetHisTransfer(ctx context.Context, req *GetHisTransferReq) (*GetHisTransferResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHisTransfer not implemented")
}

func RegisterHisTransferServer(s *grpc.Server, srv HisTransferServer) {
	s.RegisterService(&_HisTransfer_serviceDesc, srv)
}

func _HisTransfer_GetHisTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHisTransferReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HisTransferServer).GetHisTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/his_transfer.HisTransfer/GetHisTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HisTransferServer).GetHisTransfer(ctx, req.(*GetHisTransferReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _HisTransfer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "his_transfer.HisTransfer",
	HandlerType: (*HisTransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHisTransfer",
			Handler:    _HisTransfer_GetHisTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/his_transfer/his_transfer.proto",
}
