// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/base/base.proto

package base

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pagination struct {
	TotalRecord          int32    `protobuf:"varint,1,opt,name=totalRecord,proto3" json:"totalRecord"`
	CurrentPage          int32    `protobuf:"varint,2,opt,name=currentPage,proto3" json:"currentPage"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize"`
	TotalPages           int32    `protobuf:"varint,4,opt,name=totalPages,proto3" json:"totalPages"`
	HasNext              bool     `protobuf:"varint,5,opt,name=hasNext,proto3" json:"hasNext"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_e56de8d0620b9cff, []int{0}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetTotalRecord() int32 {
	if m != nil {
		return m.TotalRecord
	}
	return 0
}

func (m *Pagination) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *Pagination) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Pagination) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *Pagination) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

func init() {
	proto.RegisterType((*Pagination)(nil), "base.Pagination")
}

func init() { proto.RegisterFile("proto/base/base.proto", fileDescriptor_e56de8d0620b9cff) }

var fileDescriptor_e56de8d0620b9cff = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4a, 0x2c, 0x4e, 0x05, 0x13, 0x7a, 0x60, 0xbe, 0x10, 0x0b, 0x88, 0xad, 0xb4,
	0x8c, 0x91, 0x8b, 0x2b, 0x20, 0x31, 0x3d, 0x33, 0x2f, 0xb1, 0x24, 0x33, 0x3f, 0x4f, 0x48, 0x81,
	0x8b, 0xbb, 0x24, 0xbf, 0x24, 0x31, 0x27, 0x28, 0x35, 0x39, 0xbf, 0x28, 0x45, 0x82, 0x51, 0x81,
	0x51, 0x83, 0x35, 0x08, 0x59, 0x08, 0xa4, 0x22, 0xb9, 0xb4, 0xa8, 0x28, 0x35, 0xaf, 0x24, 0x20,
	0x31, 0x3d, 0x55, 0x82, 0x09, 0xa2, 0x02, 0x49, 0x48, 0x48, 0x8a, 0x8b, 0xa3, 0x20, 0x31, 0x3d,
	0x35, 0x38, 0xb3, 0x2a, 0x55, 0x82, 0x19, 0x2c, 0x0d, 0xe7, 0x0b, 0xc9, 0x71, 0x71, 0x81, 0x0d,
	0x03, 0x29, 0x2c, 0x96, 0x60, 0x01, 0xcb, 0x22, 0x89, 0x08, 0x49, 0x70, 0xb1, 0x67, 0x24, 0x16,
	0xfb, 0xa5, 0x56, 0x94, 0x48, 0xb0, 0x2a, 0x30, 0x6a, 0x70, 0x04, 0xc1, 0xb8, 0x4e, 0x1a, 0x51,
	0x6a, 0xe9, 0x99, 0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xce, 0x41, 0xfe, 0x41,
	0xce, 0x41, 0xfa, 0xc9, 0x45, 0xba, 0xc9, 0xf9, 0xb9, 0xb9, 0xf9, 0x79, 0xfa, 0x08, 0x3f, 0x26,
	0xb1, 0x81, 0xd9, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0xf5, 0x7f, 0x2e, 0xf8, 0x00,
	0x00, 0x00,
}
