// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/engine_order/order.proto

package his_order

import (
	context "context"
	fmt "fmt"
	base "github.com/CRORCR/cr-common/proto/base"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetOrderReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	MakerOrder           string   `protobuf:"bytes,2,opt,name=makerOrder,proto3" json:"makerOrder"`
	TakerOrder           string   `protobuf:"bytes,3,opt,name=takerOrder,proto3" json:"takerOrder"`
	Side                 string   `protobuf:"bytes,4,opt,name=side,proto3" json:"side"`
	StartTime            string   `protobuf:"bytes,5,opt,name=startTime,proto3" json:"startTime"`
	EndTime              string   `protobuf:"bytes,6,opt,name=endTime,proto3" json:"endTime"`
	Symbol               string   `protobuf:"bytes,7,opt,name=symbol,proto3" json:"symbol"`
	Page                 int32    `protobuf:"varint,8,opt,name=Page,proto3" json:"Page"`
	Size                 int32    `protobuf:"varint,9,opt,name=Size,proto3" json:"Size"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderReq) Reset()         { *m = GetOrderReq{} }
func (m *GetOrderReq) String() string { return proto.CompactTextString(m) }
func (*GetOrderReq) ProtoMessage()    {}
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2c507e7584a5c5, []int{0}
}

func (m *GetOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderReq.Unmarshal(m, b)
}
func (m *GetOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderReq.Marshal(b, m, deterministic)
}
func (m *GetOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderReq.Merge(m, src)
}
func (m *GetOrderReq) XXX_Size() int {
	return xxx_messageInfo_GetOrderReq.Size(m)
}
func (m *GetOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderReq proto.InternalMessageInfo

func (m *GetOrderReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetOrderReq) GetMakerOrder() string {
	if m != nil {
		return m.MakerOrder
	}
	return ""
}

func (m *GetOrderReq) GetTakerOrder() string {
	if m != nil {
		return m.TakerOrder
	}
	return ""
}

func (m *GetOrderReq) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *GetOrderReq) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetOrderReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *GetOrderReq) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetOrderReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetOrderReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetOrderResp struct {
	Status               int32                `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg                  string               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	Data                 []*GetOrderResp_Data `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
	Pag                  *base.Pagination     `protobuf:"bytes,4,opt,name=pag,proto3" json:"pag"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GetOrderResp) Reset()         { *m = GetOrderResp{} }
func (m *GetOrderResp) String() string { return proto.CompactTextString(m) }
func (*GetOrderResp) ProtoMessage()    {}
func (*GetOrderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2c507e7584a5c5, []int{1}
}

func (m *GetOrderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResp.Unmarshal(m, b)
}
func (m *GetOrderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResp.Marshal(b, m, deterministic)
}
func (m *GetOrderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResp.Merge(m, src)
}
func (m *GetOrderResp) XXX_Size() int {
	return xxx_messageInfo_GetOrderResp.Size(m)
}
func (m *GetOrderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResp proto.InternalMessageInfo

func (m *GetOrderResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetOrderResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetOrderResp) GetData() []*GetOrderResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetOrderResp) GetPag() *base.Pagination {
	if m != nil {
		return m.Pag
	}
	return nil
}

type GetOrderResp_Data struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Timestamp            string   `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp"`
	MakerOrderID         string   `protobuf:"bytes,3,opt,name=makerOrderID,proto3" json:"makerOrderID"`
	TakerOrderID         string   `protobuf:"bytes,4,opt,name=takerOrderID,proto3" json:"takerOrderID"`
	Side                 string   `protobuf:"bytes,5,opt,name=side,proto3" json:"side"`
	Size                 float32  `protobuf:"fixed32,6,opt,name=size,proto3" json:"size"`
	Price                float32  `protobuf:"fixed32,7,opt,name=price,proto3" json:"price"`
	Symbol               string   `protobuf:"bytes,8,opt,name=symbol,proto3" json:"symbol"`
	MakerFeeTotal        float32  `protobuf:"fixed32,9,opt,name=makerFeeTotal,proto3" json:"makerFeeTotal"`
	TakerFeeTotal        float32  `protobuf:"fixed32,10,opt,name=takerFeeTotal,proto3" json:"takerFeeTotal"`
	MakerFeeCurrency     string   `protobuf:"bytes,11,opt,name=makerFeeCurrency,proto3" json:"makerFeeCurrency"`
	TakerFeeCurrency     string   `protobuf:"bytes,12,opt,name=takerFeeCurrency,proto3" json:"takerFeeCurrency"`
	MakerAccount         string   `protobuf:"bytes,13,opt,name=makerAccount,proto3" json:"makerAccount"`
	TakerAccount         string   `protobuf:"bytes,14,opt,name=takerAccount,proto3" json:"takerAccount"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOrderResp_Data) Reset()         { *m = GetOrderResp_Data{} }
func (m *GetOrderResp_Data) String() string { return proto.CompactTextString(m) }
func (*GetOrderResp_Data) ProtoMessage()    {}
func (*GetOrderResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d2c507e7584a5c5, []int{1, 0}
}

func (m *GetOrderResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOrderResp_Data.Unmarshal(m, b)
}
func (m *GetOrderResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOrderResp_Data.Marshal(b, m, deterministic)
}
func (m *GetOrderResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOrderResp_Data.Merge(m, src)
}
func (m *GetOrderResp_Data) XXX_Size() int {
	return xxx_messageInfo_GetOrderResp_Data.Size(m)
}
func (m *GetOrderResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOrderResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetOrderResp_Data proto.InternalMessageInfo

func (m *GetOrderResp_Data) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetOrderResp_Data) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *GetOrderResp_Data) GetMakerOrderID() string {
	if m != nil {
		return m.MakerOrderID
	}
	return ""
}

func (m *GetOrderResp_Data) GetTakerOrderID() string {
	if m != nil {
		return m.TakerOrderID
	}
	return ""
}

func (m *GetOrderResp_Data) GetSide() string {
	if m != nil {
		return m.Side
	}
	return ""
}

func (m *GetOrderResp_Data) GetSize() float32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetOrderResp_Data) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GetOrderResp_Data) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *GetOrderResp_Data) GetMakerFeeTotal() float32 {
	if m != nil {
		return m.MakerFeeTotal
	}
	return 0
}

func (m *GetOrderResp_Data) GetTakerFeeTotal() float32 {
	if m != nil {
		return m.TakerFeeTotal
	}
	return 0
}

func (m *GetOrderResp_Data) GetMakerFeeCurrency() string {
	if m != nil {
		return m.MakerFeeCurrency
	}
	return ""
}

func (m *GetOrderResp_Data) GetTakerFeeCurrency() string {
	if m != nil {
		return m.TakerFeeCurrency
	}
	return ""
}

func (m *GetOrderResp_Data) GetMakerAccount() string {
	if m != nil {
		return m.MakerAccount
	}
	return ""
}

func (m *GetOrderResp_Data) GetTakerAccount() string {
	if m != nil {
		return m.TakerAccount
	}
	return ""
}

func init() {
	proto.RegisterType((*GetOrderReq)(nil), "engine_order.GetOrderReq")
	proto.RegisterType((*GetOrderResp)(nil), "engine_order.GetOrderResp")
	proto.RegisterType((*GetOrderResp_Data)(nil), "engine_order.GetOrderResp.Data")
}

func init() { proto.RegisterFile("proto/engine_order/order.proto", fileDescriptor_5d2c507e7584a5c5) }

var fileDescriptor_5d2c507e7584a5c5 = []byte{
	// 506 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x86, 0x69, 0xd2, 0x76, 0xeb, 0x69, 0x37, 0x55, 0x16, 0x20, 0x53, 0xa1, 0x51, 0x55, 0x5c,
	0x54, 0xa0, 0xa5, 0x52, 0xf7, 0x04, 0xd0, 0x69, 0x80, 0x84, 0xd4, 0xc9, 0xf4, 0x8a, 0x1b, 0xe4,
	0x26, 0x56, 0x66, 0xb1, 0xc4, 0x5d, 0x7c, 0x72, 0xb1, 0x3d, 0x1c, 0x0f, 0xc1, 0x7b, 0xf0, 0x0e,
	0xc8, 0xc7, 0x69, 0x93, 0x6c, 0xda, 0x4d, 0x74, 0xfc, 0xfd, 0xbf, 0x9d, 0x9c, 0xff, 0x38, 0x70,
	0xb6, 0x2b, 0x0c, 0x9a, 0x85, 0xca, 0x53, 0x9d, 0xab, 0x5f, 0xa6, 0x48, 0x54, 0xb1, 0xa0, 0x67,
	0x44, 0x02, 0x1b, 0x35, 0x95, 0xc9, 0x2b, 0xef, 0xde, 0x4a, 0xab, 0xe8, 0xe1, 0x4d, 0xb3, 0x7f,
	0x1d, 0x18, 0x7e, 0x51, 0xb8, 0x76, 0x1e, 0xa1, 0xee, 0x18, 0x83, 0x6e, 0x59, 0xea, 0x84, 0x77,
	0xa6, 0x9d, 0xf9, 0x40, 0x50, 0xcd, 0xce, 0x00, 0x32, 0xf9, 0x5b, 0x15, 0x64, 0xe2, 0x01, 0x29,
	0x0d, 0xe2, 0x74, 0xac, 0xf5, 0xd0, 0xeb, 0x35, 0x71, 0x67, 0x5a, 0x9d, 0x28, 0xde, 0xf5, 0x67,
	0xba, 0x9a, 0xbd, 0x85, 0x81, 0x45, 0x59, 0xe0, 0x46, 0x67, 0x8a, 0xf7, 0x48, 0xa8, 0x01, 0xe3,
	0x70, 0xa4, 0xf2, 0x84, 0xb4, 0x3e, 0x69, 0xfb, 0x25, 0x7b, 0x0d, 0x7d, 0x7b, 0x9f, 0x6d, 0xcd,
	0x2d, 0x3f, 0x22, 0xa1, 0x5a, 0xb9, 0x77, 0x5c, 0xcb, 0x54, 0xf1, 0xe3, 0x69, 0x67, 0xde, 0x13,
	0x54, 0x3b, 0xf6, 0x43, 0x3f, 0x28, 0x3e, 0xf0, 0xcc, 0xd5, 0xb3, 0xbf, 0x5d, 0x18, 0xd5, 0xfd,
	0xda, 0x1d, 0x1d, 0x88, 0x12, 0x4b, 0x4b, 0x2d, 0xf7, 0x44, 0xb5, 0x62, 0x63, 0x08, 0x33, 0x9b,
	0x56, 0xdd, 0xba, 0x92, 0x5d, 0x40, 0x37, 0x91, 0x28, 0x79, 0x38, 0x0d, 0xe7, 0xc3, 0xe5, 0xbb,
	0xa8, 0x19, 0x6f, 0xd4, 0x3c, 0x33, 0xba, 0x94, 0x28, 0x05, 0x99, 0xd9, 0x0c, 0xc2, 0x9d, 0x4c,
	0xa9, 0xf5, 0xe1, 0x72, 0x1c, 0x51, 0xf2, 0xd7, 0x32, 0xd5, 0xb9, 0x44, 0x6d, 0x72, 0xe1, 0xc4,
	0xc9, 0x9f, 0x10, 0xba, 0x6e, 0x0b, 0x3b, 0x85, 0xe0, 0x10, 0x7d, 0xa0, 0x13, 0x17, 0x12, 0xea,
	0x4c, 0x59, 0x94, 0xd9, 0xae, 0xfa, 0x92, 0x1a, 0xb0, 0x19, 0x8c, 0xea, 0x21, 0x7c, 0xbb, 0xac,
	0x82, 0x6f, 0x31, 0xe7, 0xc1, 0xa6, 0xc7, 0x8f, 0xa0, 0xc5, 0x0e, 0xe3, 0xe9, 0x35, 0xc6, 0x43,
	0xec, 0xc1, 0xa7, 0x1f, 0x08, 0xaa, 0xd9, 0x4b, 0xe8, 0xed, 0x0a, 0x1d, 0x2b, 0x4a, 0x3e, 0x10,
	0x7e, 0xd1, 0x18, 0xc8, 0x71, 0x6b, 0x20, 0xef, 0xe1, 0x84, 0xbe, 0xe4, 0x4a, 0xa9, 0x8d, 0x41,
	0x79, 0x4b, 0x53, 0x08, 0x44, 0x1b, 0x3a, 0x17, 0xb6, 0x5c, 0xe0, 0x5d, 0x2d, 0xc8, 0x3e, 0xc0,
	0x78, 0xbf, 0x6d, 0x55, 0x16, 0x85, 0xca, 0xe3, 0x7b, 0x3e, 0xa4, 0xb7, 0x3d, 0xe1, 0xce, 0x8b,
	0x8f, 0xbd, 0x23, 0xef, 0x7d, 0xcc, 0x0f, 0x09, 0x7e, 0x8a, 0x63, 0x53, 0xe6, 0xc8, 0x4f, 0x1a,
	0x09, 0x56, 0xec, 0x90, 0xe0, 0xde, 0x73, 0xda, 0x48, 0xb0, 0x62, 0xcb, 0x0d, 0xc0, 0x57, 0x6d,
	0xd7, 0x18, 0x7f, 0xd7, 0x16, 0xd9, 0x15, 0xfd, 0x51, 0x0e, 0xd0, 0xed, 0x7f, 0xf3, 0xdc, 0x45,
	0xb9, 0x9b, 0x4c, 0x9e, 0xbf, 0x43, 0xb3, 0x17, 0x9f, 0xcf, 0x7f, 0x7e, 0x4c, 0x35, 0xde, 0x94,
	0xdb, 0x28, 0x36, 0xd9, 0x62, 0x25, 0xd6, 0x62, 0x25, 0x16, 0x71, 0x71, 0x1e, 0x9b, 0x2c, 0x33,
	0xf9, 0xc2, 0xff, 0xcf, 0x37, 0xda, 0xfa, 0xdd, 0xdb, 0x3e, 0x81, 0x8b, 0xff, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xfb, 0xb6, 0x13, 0xb4, 0x17, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HisOtcListClient is the client API for HisOtcList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HisOtcListClient interface {
	GetHisOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error)
}

type hisOtcListClient struct {
	cc *grpc.ClientConn
}

func NewHisOtcListClient(cc *grpc.ClientConn) HisOtcListClient {
	return &hisOtcListClient{cc}
}

func (c *hisOtcListClient) GetHisOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	out := new(GetOrderResp)
	err := c.cc.Invoke(ctx, "/engine_order.HisOtcList/GetHisOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HisOtcListServer is the server API for HisOtcList service.
type HisOtcListServer interface {
	GetHisOrder(context.Context, *GetOrderReq) (*GetOrderResp, error)
}

// UnimplementedHisOtcListServer can be embedded to have forward compatible implementations.
type UnimplementedHisOtcListServer struct {
}

func (*UnimplementedHisOtcListServer) GetHisOrder(ctx context.Context, req *GetOrderReq) (*GetOrderResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHisOrder not implemented")
}

func RegisterHisOtcListServer(s *grpc.Server, srv HisOtcListServer) {
	s.RegisterService(&_HisOtcList_serviceDesc, srv)
}

func _HisOtcList_GetHisOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HisOtcListServer).GetHisOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/engine_order.HisOtcList/GetHisOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HisOtcListServer).GetHisOrder(ctx, req.(*GetOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _HisOtcList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "engine_order.HisOtcList",
	HandlerType: (*HisOtcListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHisOrder",
			Handler:    _HisOtcList_GetHisOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/engine_order/order.proto",
}
