// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/partner/user.proto

package partner

import (
	context "context"
	fmt "fmt"
	base "github.com/CRORCR/cr-common/proto/base"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddUserReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Project              string   `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	Rate                 string   `protobuf:"bytes,5,opt,name=rate,proto3" json:"rate,omitempty"`
	Currency             string   `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	PreInviteUserId      string   `protobuf:"bytes,7,opt,name=pre_invite_user_id,json=preInviteUserId,proto3" json:"pre_invite_user_id,omitempty"`
	PreInviteUserName    string   `protobuf:"bytes,8,opt,name=pre_invite_user_name,json=preInviteUserName,proto3" json:"pre_invite_user_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserReq) Reset()         { *m = AddUserReq{} }
func (m *AddUserReq) String() string { return proto.CompactTextString(m) }
func (*AddUserReq) ProtoMessage()    {}
func (*AddUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd5995376941cb7b, []int{0}
}

func (m *AddUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserReq.Unmarshal(m, b)
}
func (m *AddUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserReq.Marshal(b, m, deterministic)
}
func (m *AddUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserReq.Merge(m, src)
}
func (m *AddUserReq) XXX_Size() int {
	return xxx_messageInfo_AddUserReq.Size(m)
}
func (m *AddUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserReq proto.InternalMessageInfo

func (m *AddUserReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AddUserReq) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *AddUserReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddUserReq) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *AddUserReq) GetRate() string {
	if m != nil {
		return m.Rate
	}
	return ""
}

func (m *AddUserReq) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *AddUserReq) GetPreInviteUserId() string {
	if m != nil {
		return m.PreInviteUserId
	}
	return ""
}

func (m *AddUserReq) GetPreInviteUserName() string {
	if m != nil {
		return m.PreInviteUserName
	}
	return ""
}

type AddUserResp struct {
	Date                 string   `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	ErrorMessage         string   `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResp) Reset()         { *m = AddUserResp{} }
func (m *AddUserResp) String() string { return proto.CompactTextString(m) }
func (*AddUserResp) ProtoMessage()    {}
func (*AddUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd5995376941cb7b, []int{1}
}

func (m *AddUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResp.Unmarshal(m, b)
}
func (m *AddUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResp.Marshal(b, m, deterministic)
}
func (m *AddUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResp.Merge(m, src)
}
func (m *AddUserResp) XXX_Size() int {
	return xxx_messageInfo_AddUserResp.Size(m)
}
func (m *AddUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResp proto.InternalMessageInfo

func (m *AddUserResp) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *AddUserResp) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

//查询合伙人
type GetUserReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PreInviteUserId      string   `protobuf:"bytes,2,opt,name=pre_invite_user_id,json=preInviteUserId,proto3" json:"pre_invite_user_id,omitempty"`
	StartTime            string   `protobuf:"bytes,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Level                string   `protobuf:"bytes,5,opt,name=level,proto3" json:"level,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Page                 int32    `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	Size                 int32    `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReq) Reset()         { *m = GetUserReq{} }
func (m *GetUserReq) String() string { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()    {}
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd5995376941cb7b, []int{2}
}

func (m *GetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReq.Unmarshal(m, b)
}
func (m *GetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReq.Marshal(b, m, deterministic)
}
func (m *GetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReq.Merge(m, src)
}
func (m *GetUserReq) XXX_Size() int {
	return xxx_messageInfo_GetUserReq.Size(m)
}
func (m *GetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReq proto.InternalMessageInfo

func (m *GetUserReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetUserReq) GetPreInviteUserId() string {
	if m != nil {
		return m.PreInviteUserId
	}
	return ""
}

func (m *GetUserReq) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetUserReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *GetUserReq) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *GetUserReq) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GetUserReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetUserReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetUserResp struct {
	Data                 []*GetUserResp_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination           *base.Pagination    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *GetUserResp) Reset()         { *m = GetUserResp{} }
func (m *GetUserResp) String() string { return proto.CompactTextString(m) }
func (*GetUserResp) ProtoMessage()    {}
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd5995376941cb7b, []int{3}
}

func (m *GetUserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResp.Unmarshal(m, b)
}
func (m *GetUserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResp.Marshal(b, m, deterministic)
}
func (m *GetUserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResp.Merge(m, src)
}
func (m *GetUserResp) XXX_Size() int {
	return xxx_messageInfo_GetUserResp.Size(m)
}
func (m *GetUserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResp proto.InternalMessageInfo

func (m *GetUserResp) GetData() []*GetUserResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetUserResp) GetPagination() *base.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetUserResp_Data struct {
	PreInviteUserId      string   `protobuf:"bytes,1,opt,name=pre_invite_user_id,json=preInviteUserId,proto3" json:"pre_invite_user_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Rate                 string   `protobuf:"bytes,4,opt,name=rate,proto3" json:"rate,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Project              string   `protobuf:"bytes,6,opt,name=project,proto3" json:"project,omitempty"`
	Currency             string   `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt            string   `protobuf:"bytes,8,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,9,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResp_Data) Reset()         { *m = GetUserResp_Data{} }
func (m *GetUserResp_Data) String() string { return proto.CompactTextString(m) }
func (*GetUserResp_Data) ProtoMessage()    {}
func (*GetUserResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd5995376941cb7b, []int{3, 0}
}

func (m *GetUserResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResp_Data.Unmarshal(m, b)
}
func (m *GetUserResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResp_Data.Marshal(b, m, deterministic)
}
func (m *GetUserResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResp_Data.Merge(m, src)
}
func (m *GetUserResp_Data) XXX_Size() int {
	return xxx_messageInfo_GetUserResp_Data.Size(m)
}
func (m *GetUserResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResp_Data proto.InternalMessageInfo

func (m *GetUserResp_Data) GetPreInviteUserId() string {
	if m != nil {
		return m.PreInviteUserId
	}
	return ""
}

func (m *GetUserResp_Data) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetUserResp_Data) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserResp_Data) GetRate() string {
	if m != nil {
		return m.Rate
	}
	return ""
}

func (m *GetUserResp_Data) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *GetUserResp_Data) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *GetUserResp_Data) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetUserResp_Data) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetUserResp_Data) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type NoticeReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeReq) Reset()         { *m = NoticeReq{} }
func (m *NoticeReq) String() string { return proto.CompactTextString(m) }
func (*NoticeReq) ProtoMessage()    {}
func (*NoticeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd5995376941cb7b, []int{4}
}

func (m *NoticeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeReq.Unmarshal(m, b)
}
func (m *NoticeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeReq.Marshal(b, m, deterministic)
}
func (m *NoticeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeReq.Merge(m, src)
}
func (m *NoticeReq) XXX_Size() int {
	return xxx_messageInfo_NoticeReq.Size(m)
}
func (m *NoticeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeReq.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeReq proto.InternalMessageInfo

func (m *NoticeReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type NoticeResp struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NoticeResp) Reset()         { *m = NoticeResp{} }
func (m *NoticeResp) String() string { return proto.CompactTextString(m) }
func (*NoticeResp) ProtoMessage()    {}
func (*NoticeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd5995376941cb7b, []int{5}
}

func (m *NoticeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NoticeResp.Unmarshal(m, b)
}
func (m *NoticeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NoticeResp.Marshal(b, m, deterministic)
}
func (m *NoticeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoticeResp.Merge(m, src)
}
func (m *NoticeResp) XXX_Size() int {
	return xxx_messageInfo_NoticeResp.Size(m)
}
func (m *NoticeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NoticeResp.DiscardUnknown(m)
}

var xxx_messageInfo_NoticeResp proto.InternalMessageInfo

func (m *NoticeResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *NoticeResp) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NoticeResp) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*AddUserReq)(nil), "partner.AddUserReq")
	proto.RegisterType((*AddUserResp)(nil), "partner.AddUserResp")
	proto.RegisterType((*GetUserReq)(nil), "partner.GetUserReq")
	proto.RegisterType((*GetUserResp)(nil), "partner.GetUserResp")
	proto.RegisterType((*GetUserResp_Data)(nil), "partner.GetUserResp.Data")
	proto.RegisterType((*NoticeReq)(nil), "partner.NoticeReq")
	proto.RegisterType((*NoticeResp)(nil), "partner.NoticeResp")
}

func init() { proto.RegisterFile("proto/partner/user.proto", fileDescriptor_cd5995376941cb7b) }

var fileDescriptor_cd5995376941cb7b = []byte{
	// 580 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0xd3, 0x24, 0x6e, 0x26, 0x45, 0xc0, 0xb6, 0x80, 0x89, 0x7a, 0xa8, 0x0c, 0x87, 0xa2,
	0xaa, 0x36, 0x0a, 0x12, 0x12, 0xc7, 0x52, 0x44, 0xd5, 0x03, 0x05, 0x19, 0x7a, 0xe1, 0x12, 0x6d,
	0xec, 0x51, 0x30, 0x8a, 0xbd, 0xcb, 0xee, 0xa6, 0x52, 0xf9, 0x57, 0xfc, 0x1f, 0xfe, 0x03, 0x67,
	0x2e, 0x08, 0xed, 0x87, 0xbf, 0xda, 0x14, 0x2e, 0xd1, 0xcc, 0x9b, 0x37, 0xd1, 0xbc, 0xe7, 0x67,
	0x43, 0xc0, 0x05, 0x53, 0x2c, 0xe6, 0x54, 0xa8, 0x12, 0x45, 0xbc, 0x92, 0x28, 0x22, 0x03, 0x11,
	0xdf, 0x61, 0x93, 0x07, 0x96, 0x32, 0xa7, 0x12, 0xcd, 0x8f, 0x9d, 0x87, 0xbf, 0x3d, 0x80, 0xe3,
	0x2c, 0xbb, 0x90, 0x28, 0x12, 0xfc, 0x46, 0x1e, 0x81, 0xaf, 0x97, 0x67, 0x79, 0x16, 0x78, 0xfb,
	0xde, 0xc1, 0x28, 0x19, 0xea, 0xf6, 0x2c, 0x23, 0x0f, 0x61, 0x58, 0xb0, 0x79, 0xbe, 0xc4, 0xa0,
	0x67, 0x71, 0xdb, 0x11, 0x02, 0xfd, 0x92, 0x16, 0x18, 0x6c, 0x1a, 0xd4, 0xd4, 0x24, 0x00, 0x9f,
	0x0b, 0xf6, 0x15, 0x53, 0x15, 0xf4, 0x0d, 0x5c, 0xb5, 0x9a, 0x2d, 0xa8, 0xc2, 0x60, 0x60, 0xd9,
	0xba, 0x26, 0x13, 0xd8, 0x4a, 0x57, 0x42, 0x60, 0x99, 0x5e, 0x05, 0x43, 0x83, 0xd7, 0x3d, 0x39,
	0x04, 0xc2, 0x05, 0xce, 0xf2, 0xf2, 0x32, 0x57, 0x38, 0xab, 0x2e, 0xf3, 0x0d, 0xeb, 0x2e, 0x17,
	0x78, 0x66, 0x06, 0x17, 0xf6, 0xc4, 0x18, 0x76, 0xaf, 0x93, 0xcd, 0x69, 0x5b, 0x86, 0x7e, 0xbf,
	0x43, 0x3f, 0xa7, 0x05, 0x86, 0x6f, 0x61, 0x5c, 0x4b, 0x97, 0x5c, 0x1f, 0x97, 0xe9, 0xe3, 0xac,
	0x70, 0x53, 0x93, 0x27, 0x70, 0x07, 0x85, 0x60, 0x62, 0x56, 0xa0, 0x94, 0x74, 0x51, 0xa9, 0xdf,
	0x36, 0xe0, 0x3b, 0x8b, 0x85, 0x3f, 0x3d, 0x80, 0x53, 0x54, 0xff, 0xf5, 0x70, 0xbd, 0x9a, 0xde,
	0x7a, 0x35, 0x7b, 0x30, 0x92, 0x8a, 0x0a, 0xf5, 0x29, 0xaf, 0xdd, 0x6d, 0x00, 0x6d, 0x31, 0x96,
	0x99, 0x99, 0x39, 0x8b, 0x5d, 0x4b, 0x76, 0x61, 0xb0, 0xc4, 0x4b, 0x5c, 0x3a, 0x8f, 0x6d, 0xa3,
	0xb5, 0xa9, 0x2b, 0x8e, 0xce, 0x60, 0x53, 0x6b, 0x8c, 0x6b, 0x49, 0xda, 0xce, 0x41, 0x62, 0x6a,
	0x8d, 0xc9, 0xfc, 0xbb, 0xf5, 0x6c, 0x90, 0x98, 0x3a, 0xfc, 0xd5, 0x83, 0x71, 0x2d, 0x4f, 0x72,
	0x72, 0x64, 0x7c, 0xa2, 0x81, 0xb7, 0xbf, 0x79, 0x30, 0x9e, 0x3e, 0x8e, 0x5c, 0xc2, 0xa2, 0x16,
	0x27, 0x7a, 0x43, 0x15, 0x35, 0x16, 0x52, 0xf2, 0x1c, 0x80, 0xd3, 0x45, 0x5e, 0x52, 0x95, 0xb3,
	0xd2, 0xa8, 0x1d, 0x4f, 0xef, 0x45, 0x26, 0x82, 0x1f, 0x6a, 0x3c, 0x69, 0x71, 0x26, 0x7f, 0x3c,
	0xe8, 0xeb, 0x3f, 0xb8, 0xc5, 0x30, 0x6f, 0xbd, 0x61, 0x2d, 0xdb, 0x7b, 0x1d, 0xdb, 0xd7, 0x45,
	0xb4, 0x0a, 0x62, 0xbf, 0x15, 0xc4, 0x26, 0xe2, 0x83, 0x4e, 0xc4, 0x5b, 0x71, 0x1e, 0x76, 0xe3,
	0xdc, 0x8e, 0xae, 0x7f, 0x2d, 0xba, 0x7b, 0x30, 0x4a, 0x05, 0x52, 0x85, 0xd9, 0xb1, 0x72, 0x11,
	0x6c, 0x00, 0x3d, 0x5d, 0xf1, 0xcc, 0x4d, 0x47, 0x76, 0x5a, 0x03, 0xe1, 0x53, 0x18, 0x9d, 0x33,
	0x95, 0xa7, 0xf8, 0xaf, 0x38, 0x85, 0x1f, 0x01, 0x2a, 0x96, 0xe4, 0xb7, 0xa7, 0xae, 0x7a, 0xf4,
	0xbd, 0xd6, 0xa3, 0x0f, 0xc0, 0x4f, 0x59, 0xa9, 0xb0, 0x54, 0xce, 0x95, 0xaa, 0x9d, 0xfe, 0xf0,
	0xa0, 0xaf, 0x0d, 0x25, 0x2f, 0xc1, 0x77, 0x2f, 0x07, 0xd9, 0xa9, 0x1f, 0x71, 0xf3, 0xa5, 0x98,
	0xec, 0xde, 0x04, 0x25, 0x0f, 0x37, 0xf4, 0x9e, 0x0b, 0x42, 0x6b, 0xaf, 0x79, 0x3b, 0x5a, 0x7b,
	0xad, 0xbc, 0x84, 0x1b, 0xe4, 0x15, 0x6c, 0x9f, 0xa2, 0x6a, 0x64, 0x93, 0x9a, 0x57, 0x63, 0x93,
	0x9d, 0x1b, 0x98, 0x5e, 0x7d, 0x7d, 0xf8, 0xf9, 0xd9, 0x22, 0x57, 0x5f, 0x56, 0xf3, 0x28, 0x65,
	0x45, 0x7c, 0x92, 0xbc, 0x4f, 0x4e, 0x92, 0x38, 0x15, 0x47, 0x29, 0x2b, 0x0a, 0x56, 0xc6, 0x9d,
	0x6f, 0xe3, 0x7c, 0x68, 0xda, 0x17, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x9c, 0x89, 0xf7,
	0x33, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error)
	GetNoticeReq(ctx context.Context, in *NoticeReq, opts ...grpc.CallOption) (*NoticeResp, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc.CallOption) (*AddUserResp, error) {
	out := new(AddUserResp)
	err := c.cc.Invoke(ctx, "/partner.User/AddUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserResp, error) {
	out := new(GetUserResp)
	err := c.cc.Invoke(ctx, "/partner.User/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetNoticeReq(ctx context.Context, in *NoticeReq, opts ...grpc.CallOption) (*NoticeResp, error) {
	out := new(NoticeResp)
	err := c.cc.Invoke(ctx, "/partner.User/GetNoticeReq", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	AddUser(context.Context, *AddUserReq) (*AddUserResp, error)
	GetUser(context.Context, *GetUserReq) (*GetUserResp, error)
	GetNoticeReq(context.Context, *NoticeReq) (*NoticeResp, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) AddUser(ctx context.Context, req *AddUserReq) (*AddUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUser not implemented")
}
func (*UnimplementedUserServer) GetUser(ctx context.Context, req *GetUserReq) (*GetUserResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServer) GetNoticeReq(ctx context.Context, req *NoticeReq) (*NoticeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNoticeReq not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).AddUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/partner.User/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).AddUser(ctx, req.(*AddUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/partner.User/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetNoticeReq_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoticeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetNoticeReq(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/partner.User/GetNoticeReq",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetNoticeReq(ctx, req.(*NoticeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "partner.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _User_AddUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _User_GetUser_Handler,
		},
		{
			MethodName: "GetNoticeReq",
			Handler:    _User_GetNoticeReq_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/partner/user.proto",
}
