// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/student/student.proto

package student

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StudentReq struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount               float32  `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentReq) Reset()         { *m = StudentReq{} }
func (m *StudentReq) String() string { return proto.CompactTextString(m) }
func (*StudentReq) ProtoMessage()    {}
func (*StudentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_3efdffaa3afda52d, []int{0}
}

func (m *StudentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentReq.Unmarshal(m, b)
}
func (m *StudentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentReq.Marshal(b, m, deterministic)
}
func (m *StudentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentReq.Merge(m, src)
}
func (m *StudentReq) XXX_Size() int {
	return xxx_messageInfo_StudentReq.Size(m)
}
func (m *StudentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentReq.DiscardUnknown(m)
}

var xxx_messageInfo_StudentReq proto.InternalMessageInfo

func (m *StudentReq) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StudentReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudentReq) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type StudentResp struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentResp) Reset()         { *m = StudentResp{} }
func (m *StudentResp) String() string { return proto.CompactTextString(m) }
func (*StudentResp) ProtoMessage()    {}
func (*StudentResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_3efdffaa3afda52d, []int{1}
}

func (m *StudentResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentResp.Unmarshal(m, b)
}
func (m *StudentResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentResp.Marshal(b, m, deterministic)
}
func (m *StudentResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentResp.Merge(m, src)
}
func (m *StudentResp) XXX_Size() int {
	return xxx_messageInfo_StudentResp.Size(m)
}
func (m *StudentResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentResp.DiscardUnknown(m)
}

var xxx_messageInfo_StudentResp proto.InternalMessageInfo

func (m *StudentResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StudentResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*StudentReq)(nil), "student.StudentReq")
	proto.RegisterType((*StudentResp)(nil), "student.StudentResp")
}

func init() { proto.RegisterFile("proto/student/student.proto", fileDescriptor_3efdffaa3afda52d) }

var fileDescriptor_3efdffaa3afda52d = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x2e, 0x29, 0x4d, 0x49, 0xcd, 0x2b, 0x81, 0xd1, 0x7a, 0x60, 0x51, 0x21, 0x76,
	0x28, 0x57, 0xc9, 0x83, 0x8b, 0x2b, 0x18, 0xc2, 0x0c, 0x4a, 0x2d, 0x14, 0xe2, 0xe3, 0x62, 0xca,
	0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x62, 0xca, 0x4c, 0x11, 0x12, 0xe2, 0x62, 0xc9,
	0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xc4, 0xb8, 0xd8,
	0x12, 0x73, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x98, 0x15, 0x18, 0x35, 0x98, 0x82, 0xa0, 0x3c, 0x25,
	0x73, 0x2e, 0x6e, 0xb8, 0x49, 0xc5, 0x05, 0x20, 0x65, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x50,
	0xe3, 0xa0, 0x3c, 0x21, 0x01, 0x2e, 0xe6, 0xdc, 0xe2, 0x74, 0xa8, 0x89, 0x20, 0xa6, 0x91, 0x3b,
	0x17, 0x97, 0x7b, 0x6a, 0x09, 0x54, 0xaf, 0x90, 0x25, 0x0a, 0x4f, 0x58, 0x0f, 0xe6, 0x6e, 0x84,
	0x2b, 0xa5, 0x44, 0x30, 0x05, 0x8b, 0x0b, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x7e, 0x33, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x4c, 0x19, 0x6a, 0x4b, 0xfa, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GetStudentClient is the client API for GetStudent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GetStudentClient interface {
	GetStudent(ctx context.Context, in *StudentReq, opts ...grpc.CallOption) (*StudentResp, error)
}

type getStudentClient struct {
	cc *grpc.ClientConn
}

func NewGetStudentClient(cc *grpc.ClientConn) GetStudentClient {
	return &getStudentClient{cc}
}

func (c *getStudentClient) GetStudent(ctx context.Context, in *StudentReq, opts ...grpc.CallOption) (*StudentResp, error) {
	out := new(StudentResp)
	err := c.cc.Invoke(ctx, "/student.GetStudent/GetStudent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStudentServer is the server API for GetStudent service.
type GetStudentServer interface {
	GetStudent(context.Context, *StudentReq) (*StudentResp, error)
}

// UnimplementedGetStudentServer can be embedded to have forward compatible implementations.
type UnimplementedGetStudentServer struct {
}

func (*UnimplementedGetStudentServer) GetStudent(ctx context.Context, req *StudentReq) (*StudentResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudent not implemented")
}

func RegisterGetStudentServer(s *grpc.Server, srv GetStudentServer) {
	s.RegisterService(&_GetStudent_serviceDesc, srv)
}

func _GetStudent_GetStudent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StudentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetStudentServer).GetStudent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/student.GetStudent/GetStudent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetStudentServer).GetStudent(ctx, req.(*StudentReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GetStudent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "student.GetStudent",
	HandlerType: (*GetStudentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudent",
			Handler:    _GetStudent_GetStudent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/student/student.proto",
}
