// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/his_wallet/his_wallet.proto

package his_wallet

import (
	context "context"
	fmt "fmt"
	base "github.com/CRORCR/cr-common/proto/base"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetWalletReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status"`
	StartTime            string   `protobuf:"bytes,4,opt,name=startTime,proto3" json:"startTime"`
	EndTime              string   `protobuf:"bytes,5,opt,name=endTime,proto3" json:"endTime"`
	Page                 int32    `protobuf:"varint,6,opt,name=page,proto3" json:"page"`
	Size                 int32    `protobuf:"varint,7,opt,name=size,proto3" json:"size"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletReq) Reset()         { *m = GetWalletReq{} }
func (m *GetWalletReq) String() string { return proto.CompactTextString(m) }
func (*GetWalletReq) ProtoMessage()    {}
func (*GetWalletReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1097521bfd08498, []int{0}
}

func (m *GetWalletReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletReq.Unmarshal(m, b)
}
func (m *GetWalletReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletReq.Marshal(b, m, deterministic)
}
func (m *GetWalletReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletReq.Merge(m, src)
}
func (m *GetWalletReq) XXX_Size() int {
	return xxx_messageInfo_GetWalletReq.Size(m)
}
func (m *GetWalletReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletReq proto.InternalMessageInfo

func (m *GetWalletReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetWalletReq) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetWalletReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetWalletReq) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetWalletReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *GetWalletReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetWalletReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type GetDepositResp struct {
	Data                 []*GetDepositResp_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data"`
	Pagination           *base.Pagination       `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetDepositResp) Reset()         { *m = GetDepositResp{} }
func (m *GetDepositResp) String() string { return proto.CompactTextString(m) }
func (*GetDepositResp) ProtoMessage()    {}
func (*GetDepositResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1097521bfd08498, []int{1}
}

func (m *GetDepositResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDepositResp.Unmarshal(m, b)
}
func (m *GetDepositResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDepositResp.Marshal(b, m, deterministic)
}
func (m *GetDepositResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDepositResp.Merge(m, src)
}
func (m *GetDepositResp) XXX_Size() int {
	return xxx_messageInfo_GetDepositResp.Size(m)
}
func (m *GetDepositResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDepositResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDepositResp proto.InternalMessageInfo

func (m *GetDepositResp) GetData() []*GetDepositResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetDepositResp) GetPagination() *base.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetDepositResp_Data struct {
	EngineAccount        string   `protobuf:"bytes,1,opt,name=engineAccount,proto3" json:"uuid"`
	Mark                 string   `protobuf:"bytes,2,opt,name=mark,proto3" json:"mark"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag"`
	OutputIndex          int32    `protobuf:"varint,4,opt,name=outputIndex,proto3" json:"outputIndex"`
	Confirmations        int32    `protobuf:"varint,5,opt,name=confirmations,proto3" json:"confirmations"`
	TxId                 string   `protobuf:"bytes,6,opt,name=txId,proto3" json:"txId"`
	Height               string   `protobuf:"bytes,7,opt,name=height,proto3" json:"height"`
	Address              string   `protobuf:"bytes,8,opt,name=address,proto3" json:"address"`
	SourceAddress        string   `protobuf:"bytes,9,opt,name=sourceAddress,proto3" json:"sourceAddress"`
	Status               int32    `protobuf:"varint,10,opt,name=status,proto3" json:"status"`
	Amount               float32  `protobuf:"fixed32,11,opt,name=amount,proto3" json:"amount"`
	UserId               int32    `protobuf:"varint,12,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Currency             string   `protobuf:"bytes,13,opt,name=currency,proto3" json:"currency"`
	CreatedAt            string   `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt"`
	UpdatedAt            string   `protobuf:"bytes,15,opt,name=updatedAt,proto3" json:"updatedAt"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDepositResp_Data) Reset()         { *m = GetDepositResp_Data{} }
func (m *GetDepositResp_Data) String() string { return proto.CompactTextString(m) }
func (*GetDepositResp_Data) ProtoMessage()    {}
func (*GetDepositResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1097521bfd08498, []int{1, 0}
}

func (m *GetDepositResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDepositResp_Data.Unmarshal(m, b)
}
func (m *GetDepositResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDepositResp_Data.Marshal(b, m, deterministic)
}
func (m *GetDepositResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDepositResp_Data.Merge(m, src)
}
func (m *GetDepositResp_Data) XXX_Size() int {
	return xxx_messageInfo_GetDepositResp_Data.Size(m)
}
func (m *GetDepositResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDepositResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetDepositResp_Data proto.InternalMessageInfo

func (m *GetDepositResp_Data) GetEngineAccount() string {
	if m != nil {
		return m.EngineAccount
	}
	return ""
}

func (m *GetDepositResp_Data) GetMark() string {
	if m != nil {
		return m.Mark
	}
	return ""
}

func (m *GetDepositResp_Data) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GetDepositResp_Data) GetOutputIndex() int32 {
	if m != nil {
		return m.OutputIndex
	}
	return 0
}

func (m *GetDepositResp_Data) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *GetDepositResp_Data) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *GetDepositResp_Data) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *GetDepositResp_Data) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetDepositResp_Data) GetSourceAddress() string {
	if m != nil {
		return m.SourceAddress
	}
	return ""
}

func (m *GetDepositResp_Data) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetDepositResp_Data) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GetDepositResp_Data) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetDepositResp_Data) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetDepositResp_Data) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetDepositResp_Data) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GetWithdrawResp struct {
	Data                 []*GetWithdrawResp_Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data"`
	Pagination           *base.Pagination        `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetWithdrawResp) Reset()         { *m = GetWithdrawResp{} }
func (m *GetWithdrawResp) String() string { return proto.CompactTextString(m) }
func (*GetWithdrawResp) ProtoMessage()    {}
func (*GetWithdrawResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1097521bfd08498, []int{2}
}

func (m *GetWithdrawResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWithdrawResp.Unmarshal(m, b)
}
func (m *GetWithdrawResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWithdrawResp.Marshal(b, m, deterministic)
}
func (m *GetWithdrawResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWithdrawResp.Merge(m, src)
}
func (m *GetWithdrawResp) XXX_Size() int {
	return xxx_messageInfo_GetWithdrawResp.Size(m)
}
func (m *GetWithdrawResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWithdrawResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetWithdrawResp proto.InternalMessageInfo

func (m *GetWithdrawResp) GetData() []*GetWithdrawResp_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetWithdrawResp) GetPagination() *base.Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetWithdrawResp_Data struct {
	UniqueUid            string   `protobuf:"bytes,1,opt,name=uniqueUid,proto3" json:"uuid"`
	Mark                 string   `protobuf:"bytes,2,opt,name=mark,proto3" json:"mark"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag"`
	PassedAt             string   `protobuf:"bytes,4,opt,name=passedAt,proto3" json:"passedAt"`
	Confirmations        int32    `protobuf:"varint,5,opt,name=confirmations,proto3" json:"confirmations"`
	TxId                 string   `protobuf:"bytes,6,opt,name=txId,proto3" json:"txId"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status"`
	Amount               float32  `protobuf:"fixed32,8,opt,name=amount,proto3" json:"amount"`
	UserId               int32    `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id"`
	SourceAddress        string   `protobuf:"bytes,10,opt,name=sourceAddress,proto3" json:"sourceAddress"`
	Address              string   `protobuf:"bytes,11,opt,name=address,proto3" json:"address"`
	Nonce                string   `protobuf:"bytes,12,opt,name=nonce,proto3" json:"nonce"`
	Fee                  float32  `protobuf:"fixed32,13,opt,name=fee,proto3" json:"fee"`
	NetworkFee           float32  `protobuf:"fixed32,14,opt,name=network_fee,json=networkFee,proto3" json:"network_fee"`
	Currency             string   `protobuf:"bytes,15,opt,name=currency,proto3" json:"currency"`
	CreatedAt            string   `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt"`
	UpdatedAt            string   `protobuf:"bytes,17,opt,name=updatedAt,proto3" json:"updatedAt"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWithdrawResp_Data) Reset()         { *m = GetWithdrawResp_Data{} }
func (m *GetWithdrawResp_Data) String() string { return proto.CompactTextString(m) }
func (*GetWithdrawResp_Data) ProtoMessage()    {}
func (*GetWithdrawResp_Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1097521bfd08498, []int{2, 0}
}

func (m *GetWithdrawResp_Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWithdrawResp_Data.Unmarshal(m, b)
}
func (m *GetWithdrawResp_Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWithdrawResp_Data.Marshal(b, m, deterministic)
}
func (m *GetWithdrawResp_Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWithdrawResp_Data.Merge(m, src)
}
func (m *GetWithdrawResp_Data) XXX_Size() int {
	return xxx_messageInfo_GetWithdrawResp_Data.Size(m)
}
func (m *GetWithdrawResp_Data) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWithdrawResp_Data.DiscardUnknown(m)
}

var xxx_messageInfo_GetWithdrawResp_Data proto.InternalMessageInfo

func (m *GetWithdrawResp_Data) GetUniqueUid() string {
	if m != nil {
		return m.UniqueUid
	}
	return ""
}

func (m *GetWithdrawResp_Data) GetMark() string {
	if m != nil {
		return m.Mark
	}
	return ""
}

func (m *GetWithdrawResp_Data) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GetWithdrawResp_Data) GetPassedAt() string {
	if m != nil {
		return m.PassedAt
	}
	return ""
}

func (m *GetWithdrawResp_Data) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *GetWithdrawResp_Data) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *GetWithdrawResp_Data) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetWithdrawResp_Data) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GetWithdrawResp_Data) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetWithdrawResp_Data) GetSourceAddress() string {
	if m != nil {
		return m.SourceAddress
	}
	return ""
}

func (m *GetWithdrawResp_Data) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetWithdrawResp_Data) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *GetWithdrawResp_Data) GetFee() float32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *GetWithdrawResp_Data) GetNetworkFee() float32 {
	if m != nil {
		return m.NetworkFee
	}
	return 0
}

func (m *GetWithdrawResp_Data) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetWithdrawResp_Data) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetWithdrawResp_Data) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*GetWalletReq)(nil), "his_transfer.GetWalletReq")
	proto.RegisterType((*GetDepositResp)(nil), "his_transfer.GetDepositResp")
	proto.RegisterType((*GetDepositResp_Data)(nil), "his_transfer.GetDepositResp.Data")
	proto.RegisterType((*GetWithdrawResp)(nil), "his_transfer.GetWithdrawResp")
	proto.RegisterType((*GetWithdrawResp_Data)(nil), "his_transfer.GetWithdrawResp.Data")
}

func init() { proto.RegisterFile("proto/his_wallet/his_wallet.proto", fileDescriptor_b1097521bfd08498) }

var fileDescriptor_b1097521bfd08498 = []byte{
	// 670 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0xc7, 0xeb, 0xe6, 0xd3, 0x93, 0x7e, 0x9d, 0xd5, 0x39, 0x3d, 0x56, 0x54, 0x44, 0x1a, 0x71,
	0x91, 0x0b, 0x70, 0x50, 0x11, 0xdc, 0x97, 0x56, 0xb4, 0x15, 0x42, 0xa0, 0x15, 0x08, 0x89, 0x9b,
	0x6a, 0x6b, 0x4f, 0x93, 0x55, 0xeb, 0xb5, 0xbb, 0xbb, 0x56, 0x0b, 0xaf, 0xc3, 0x45, 0xdf, 0x80,
	0x67, 0x40, 0x3c, 0x15, 0xda, 0xb1, 0x93, 0xda, 0x2d, 0x8d, 0x90, 0x7a, 0x13, 0xcd, 0xfc, 0xff,
	0xfb, 0x39, 0xf3, 0xf3, 0x06, 0xb6, 0x33, 0x9d, 0xda, 0x74, 0x3c, 0x95, 0xe6, 0xf8, 0x52, 0x9c,
	0x9f, 0xa3, 0xad, 0x84, 0x21, 0x79, 0x6c, 0xc5, 0x29, 0x56, 0x0b, 0x65, 0x4e, 0x51, 0xf7, 0xff,
	0x2b, 0x26, 0x9c, 0x08, 0x83, 0xf4, 0x53, 0x0c, 0x1a, 0xfe, 0xf0, 0x60, 0xe5, 0x00, 0xed, 0x67,
	0x9a, 0xc8, 0xf1, 0x82, 0x31, 0x68, 0xe6, 0xb9, 0x8c, 0x03, 0x6f, 0xe0, 0x8d, 0x7c, 0x4e, 0x31,
	0xeb, 0x43, 0x37, 0xca, 0xb5, 0x46, 0x15, 0x7d, 0x0d, 0x96, 0x49, 0x9f, 0xe7, 0x6c, 0x13, 0xda,
	0xc6, 0x0a, 0x9b, 0x9b, 0xa0, 0x41, 0x4e, 0x99, 0xb1, 0x2d, 0xf0, 0x8d, 0x15, 0xda, 0x7e, 0x94,
	0x09, 0x06, 0x4d, 0xb2, 0x6e, 0x04, 0x16, 0x40, 0x07, 0x55, 0x4c, 0x5e, 0x8b, 0xbc, 0x59, 0xea,
	0xf6, 0xcf, 0xc4, 0x04, 0x83, 0xf6, 0xc0, 0x1b, 0xb5, 0x38, 0xc5, 0x4e, 0x33, 0xf2, 0x1b, 0x06,
	0x9d, 0x42, 0x73, 0xf1, 0xf0, 0x7b, 0x13, 0xd6, 0x0e, 0xd0, 0xee, 0x63, 0x96, 0x1a, 0x69, 0x39,
	0x9a, 0x8c, 0xbd, 0x84, 0x66, 0x2c, 0xac, 0x08, 0xbc, 0x41, 0x63, 0xd4, 0xdb, 0xd9, 0x0e, 0xab,
	0xf7, 0x0f, 0xeb, 0x63, 0xc3, 0x7d, 0x61, 0x05, 0xa7, 0xe1, 0xec, 0x39, 0x40, 0x26, 0x26, 0x52,
	0x09, 0x2b, 0x53, 0x45, 0xf7, 0xeb, 0xed, 0x6c, 0x84, 0x54, 0xa3, 0x0f, 0x73, 0x9d, 0x57, 0xc6,
	0xf4, 0xaf, 0x1b, 0xd0, 0x74, 0x0b, 0xb0, 0x27, 0xb0, 0x8a, 0x6a, 0x22, 0x15, 0xee, 0x46, 0x51,
	0x9a, 0x2b, 0x5b, 0x56, 0xad, 0x2e, 0xba, 0xe3, 0x27, 0x42, 0x9f, 0x95, 0xa5, 0xa3, 0x98, 0x6d,
	0x40, 0xc3, 0x8a, 0x49, 0x59, 0x33, 0x17, 0xb2, 0x01, 0xf4, 0xd2, 0xdc, 0x66, 0xb9, 0x3d, 0x52,
	0x31, 0x5e, 0x51, 0xc9, 0x5a, 0xbc, 0x2a, 0xb9, 0xdd, 0xa2, 0x54, 0x9d, 0x4a, 0x9d, 0xd0, 0x31,
	0x0c, 0x95, 0xae, 0xc5, 0xeb, 0xa2, 0xdb, 0xcd, 0x5e, 0x1d, 0xc5, 0x54, 0x40, 0x9f, 0x53, 0xec,
	0x9a, 0x34, 0x45, 0x39, 0x99, 0x5a, 0x2a, 0xa1, 0xcf, 0xcb, 0xcc, 0xb5, 0x41, 0xc4, 0xb1, 0x46,
	0x63, 0x82, 0x6e, 0xd1, 0x86, 0x32, 0x75, 0x7b, 0x99, 0x34, 0xd7, 0x11, 0xee, 0x96, 0xbe, 0x5f,
	0xdc, 0xac, 0x26, 0x56, 0x9a, 0x0f, 0x74, 0x94, 0x59, 0xf3, 0x37, 0xa1, 0x2d, 0x12, 0x2a, 0x48,
	0x6f, 0xe0, 0x8d, 0x96, 0x79, 0x99, 0xb1, 0xff, 0xa1, 0x93, 0x1b, 0xd4, 0xc7, 0x32, 0x0e, 0x56,
	0x8a, 0x09, 0x2e, 0x3d, 0xaa, 0x13, 0xb6, 0x7a, 0x8b, 0xb0, 0x2d, 0xf0, 0x23, 0x8d, 0xc2, 0x62,
	0xbc, 0x6b, 0x83, 0xb5, 0x82, 0xa4, 0xb9, 0xe0, 0xdc, 0x3c, 0x8b, 0x4b, 0x77, 0xbd, 0x70, 0xe7,
	0xc2, 0xf0, 0x67, 0x13, 0xd6, 0x1d, 0xde, 0xd2, 0x4e, 0x63, 0x2d, 0x2e, 0x09, 0x93, 0x57, 0x35,
	0x4c, 0x86, 0x77, 0x30, 0xa9, 0x0e, 0x7e, 0x18, 0x27, 0xbf, 0x66, 0x9c, 0xb8, 0x43, 0x2a, 0x79,
	0x91, 0xe3, 0xa7, 0xf9, 0x97, 0x75, 0x23, 0xfc, 0x25, 0x1f, 0x7d, 0xe8, 0x66, 0xc2, 0x18, 0xba,
	0x67, 0xf1, 0x3d, 0xcd, 0xf3, 0x87, 0x91, 0x51, 0x76, 0xb0, 0x73, 0x4f, 0x07, 0xbb, 0xf7, 0x75,
	0xd0, 0xaf, 0x75, 0xf0, 0x0e, 0x30, 0xf0, 0x27, 0x60, 0x2a, 0xc0, 0xf5, 0xea, 0xc0, 0xfd, 0x0b,
	0x2d, 0x95, 0xaa, 0x08, 0x09, 0x0c, 0x9f, 0x17, 0x89, 0x2b, 0xc3, 0x29, 0x22, 0x21, 0xb1, 0xcc,
	0x5d, 0xc8, 0x1e, 0x43, 0x4f, 0xa1, 0xbd, 0x4c, 0xf5, 0xd9, 0xb1, 0x73, 0xd6, 0xc8, 0x81, 0x52,
	0x7a, 0x83, 0x58, 0x43, 0x69, 0x7d, 0x11, 0x4a, 0x1b, 0x0b, 0x51, 0xfa, 0xe7, 0x16, 0x4a, 0x3b,
	0xd7, 0x1e, 0xf8, 0x87, 0xd2, 0x14, 0x2f, 0x25, 0x7b, 0x0b, 0xab, 0x07, 0x68, 0x0f, 0xa5, 0x29,
	0x1f, 0x15, 0xd6, 0xbf, 0xcb, 0xd1, 0xec, 0x4d, 0xed, 0x6f, 0x2d, 0x7a, 0x8a, 0x86, 0x4b, 0xec,
	0x1d, 0x3d, 0x65, 0x6e, 0xf1, 0x12, 0xbd, 0x85, 0xab, 0x3d, 0x5a, 0x48, 0xec, 0x70, 0xe9, 0x75,
	0xf8, 0xe5, 0xe9, 0x44, 0xda, 0x69, 0x7e, 0x12, 0x46, 0x69, 0x32, 0xde, 0xe3, 0xef, 0xf9, 0x1e,
	0x1f, 0x47, 0xfa, 0x59, 0x94, 0x26, 0x49, 0xaa, 0xc6, 0xb7, 0xff, 0x39, 0x4e, 0xda, 0xa4, 0xbc,
	0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x97, 0x2f, 0xc3, 0x88, 0x54, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HisWalletClient is the client API for HisWallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HisWalletClient interface {
	GetHisDeposit(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetDepositResp, error)
	GetHisWithdraw(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetWithdrawResp, error)
}

type hisWalletClient struct {
	cc *grpc.ClientConn
}

func NewHisWalletClient(cc *grpc.ClientConn) HisWalletClient {
	return &hisWalletClient{cc}
}

func (c *hisWalletClient) GetHisDeposit(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetDepositResp, error) {
	out := new(GetDepositResp)
	err := c.cc.Invoke(ctx, "/his_transfer.HisWallet/GetHisDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hisWalletClient) GetHisWithdraw(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetWithdrawResp, error) {
	out := new(GetWithdrawResp)
	err := c.cc.Invoke(ctx, "/his_transfer.HisWallet/GetHisWithdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HisWalletServer is the server API for HisWallet service.
type HisWalletServer interface {
	GetHisDeposit(context.Context, *GetWalletReq) (*GetDepositResp, error)
	GetHisWithdraw(context.Context, *GetWalletReq) (*GetWithdrawResp, error)
}

// UnimplementedHisWalletServer can be embedded to have forward compatible implementations.
type UnimplementedHisWalletServer struct {
}

func (*UnimplementedHisWalletServer) GetHisDeposit(ctx context.Context, req *GetWalletReq) (*GetDepositResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHisDeposit not implemented")
}
func (*UnimplementedHisWalletServer) GetHisWithdraw(ctx context.Context, req *GetWalletReq) (*GetWithdrawResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHisWithdraw not implemented")
}

func RegisterHisWalletServer(s *grpc.Server, srv HisWalletServer) {
	s.RegisterService(&_HisWallet_serviceDesc, srv)
}

func _HisWallet_GetHisDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HisWalletServer).GetHisDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/his_transfer.HisWallet/GetHisDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HisWalletServer).GetHisDeposit(ctx, req.(*GetWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HisWallet_GetHisWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HisWalletServer).GetHisWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/his_transfer.HisWallet/GetHisWithdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HisWalletServer).GetHisWithdraw(ctx, req.(*GetWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _HisWallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "his_transfer.HisWallet",
	HandlerType: (*HisWalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHisDeposit",
			Handler:    _HisWallet_GetHisDeposit_Handler,
		},
		{
			MethodName: "GetHisWithdraw",
			Handler:    _HisWallet_GetHisWithdraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/his_wallet/his_wallet.proto",
}
