// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/his_wallet/his_wallet.proto

package his_wallet

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetWalletReq struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	Currency             string   `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status"`
	StartTime            string   `protobuf:"bytes,4,opt,name=startTime,proto3" json:"startTime"`
	EndTime              string   `protobuf:"bytes,5,opt,name=endTime,proto3" json:"endTime"`
	Page                 int32    `protobuf:"varint,6,opt,name=page,proto3" json:"page"`
	Size                 int32    `protobuf:"varint,7,opt,name=size,proto3" json:"size"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWalletReq) Reset()         { *m = GetWalletReq{} }
func (m *GetWalletReq) String() string { return proto.CompactTextString(m) }
func (*GetWalletReq) ProtoMessage()    {}
func (*GetWalletReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1097521bfd08498, []int{0}
}

func (m *GetWalletReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWalletReq.Unmarshal(m, b)
}
func (m *GetWalletReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWalletReq.Marshal(b, m, deterministic)
}
func (m *GetWalletReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWalletReq.Merge(m, src)
}
func (m *GetWalletReq) XXX_Size() int {
	return xxx_messageInfo_GetWalletReq.Size(m)
}
func (m *GetWalletReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWalletReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetWalletReq proto.InternalMessageInfo

func (m *GetWalletReq) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetWalletReq) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetWalletReq) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *GetWalletReq) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetWalletReq) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *GetWalletReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetWalletReq) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Pagination struct {
	TotalRecord          int32    `protobuf:"varint,1,opt,name=totalRecord,proto3" json:"totalRecord"`
	CurrentPage          int32    `protobuf:"varint,2,opt,name=currentPage,proto3" json:"currentPage"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize"`
	TotalPages           int32    `protobuf:"varint,4,opt,name=totalPages,proto3" json:"totalPages"`
	HasNext              bool     `protobuf:"varint,5,opt,name=hasNext,proto3" json:"hasNext"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1097521bfd08498, []int{1}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetTotalRecord() int32 {
	if m != nil {
		return m.TotalRecord
	}
	return 0
}

func (m *Pagination) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *Pagination) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *Pagination) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *Pagination) GetHasNext() bool {
	if m != nil {
		return m.HasNext
	}
	return false
}

type GetDepositResp struct {
	Status               int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg                  string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	Logs                 []*GetDepositResp_Logs `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs"`
	Pagination           *Pagination            `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *GetDepositResp) Reset()         { *m = GetDepositResp{} }
func (m *GetDepositResp) String() string { return proto.CompactTextString(m) }
func (*GetDepositResp) ProtoMessage()    {}
func (*GetDepositResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1097521bfd08498, []int{2}
}

func (m *GetDepositResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDepositResp.Unmarshal(m, b)
}
func (m *GetDepositResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDepositResp.Marshal(b, m, deterministic)
}
func (m *GetDepositResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDepositResp.Merge(m, src)
}
func (m *GetDepositResp) XXX_Size() int {
	return xxx_messageInfo_GetDepositResp.Size(m)
}
func (m *GetDepositResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDepositResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetDepositResp proto.InternalMessageInfo

func (m *GetDepositResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetDepositResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetDepositResp) GetLogs() []*GetDepositResp_Logs {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *GetDepositResp) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetDepositResp_Logs struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	Mark                 string   `protobuf:"bytes,2,opt,name=mark,proto3" json:"mark"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag"`
	OutputIndex          int32    `protobuf:"varint,4,opt,name=outputIndex,proto3" json:"outputIndex"`
	Confirmations        int32    `protobuf:"varint,5,opt,name=confirmations,proto3" json:"confirmations"`
	TxId                 string   `protobuf:"bytes,6,opt,name=txId,proto3" json:"txId"`
	Height               string   `protobuf:"bytes,7,opt,name=height,proto3" json:"height"`
	Address              string   `protobuf:"bytes,8,opt,name=address,proto3" json:"address"`
	SourceAddress        string   `protobuf:"bytes,9,opt,name=sourceAddress,proto3" json:"sourceAddress"`
	Status               int32    `protobuf:"varint,10,opt,name=status,proto3" json:"status"`
	Amount               float32  `protobuf:"fixed32,11,opt,name=amount,proto3" json:"amount"`
	UserId               int32    `protobuf:"varint,12,opt,name=user_id,json=userId,proto3" json:"user_id"`
	Currency             string   `protobuf:"bytes,13,opt,name=currency,proto3" json:"currency"`
	CreatedAt            string   `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt"`
	UpdatedAt            string   `protobuf:"bytes,15,opt,name=updatedAt,proto3" json:"updatedAt"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDepositResp_Logs) Reset()         { *m = GetDepositResp_Logs{} }
func (m *GetDepositResp_Logs) String() string { return proto.CompactTextString(m) }
func (*GetDepositResp_Logs) ProtoMessage()    {}
func (*GetDepositResp_Logs) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1097521bfd08498, []int{2, 0}
}

func (m *GetDepositResp_Logs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDepositResp_Logs.Unmarshal(m, b)
}
func (m *GetDepositResp_Logs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDepositResp_Logs.Marshal(b, m, deterministic)
}
func (m *GetDepositResp_Logs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDepositResp_Logs.Merge(m, src)
}
func (m *GetDepositResp_Logs) XXX_Size() int {
	return xxx_messageInfo_GetDepositResp_Logs.Size(m)
}
func (m *GetDepositResp_Logs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDepositResp_Logs.DiscardUnknown(m)
}

var xxx_messageInfo_GetDepositResp_Logs proto.InternalMessageInfo

func (m *GetDepositResp_Logs) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetDepositResp_Logs) GetMark() string {
	if m != nil {
		return m.Mark
	}
	return ""
}

func (m *GetDepositResp_Logs) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GetDepositResp_Logs) GetOutputIndex() int32 {
	if m != nil {
		return m.OutputIndex
	}
	return 0
}

func (m *GetDepositResp_Logs) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *GetDepositResp_Logs) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *GetDepositResp_Logs) GetHeight() string {
	if m != nil {
		return m.Height
	}
	return ""
}

func (m *GetDepositResp_Logs) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetDepositResp_Logs) GetSourceAddress() string {
	if m != nil {
		return m.SourceAddress
	}
	return ""
}

func (m *GetDepositResp_Logs) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetDepositResp_Logs) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GetDepositResp_Logs) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetDepositResp_Logs) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetDepositResp_Logs) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetDepositResp_Logs) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

type GetWithdrawResp struct {
	Status               int32                   `protobuf:"varint,1,opt,name=status,proto3" json:"status"`
	Msg                  string                  `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg"`
	Logs                 []*GetWithdrawResp_Logs `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs"`
	Pagination           *Pagination             `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetWithdrawResp) Reset()         { *m = GetWithdrawResp{} }
func (m *GetWithdrawResp) String() string { return proto.CompactTextString(m) }
func (*GetWithdrawResp) ProtoMessage()    {}
func (*GetWithdrawResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1097521bfd08498, []int{3}
}

func (m *GetWithdrawResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWithdrawResp.Unmarshal(m, b)
}
func (m *GetWithdrawResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWithdrawResp.Marshal(b, m, deterministic)
}
func (m *GetWithdrawResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWithdrawResp.Merge(m, src)
}
func (m *GetWithdrawResp) XXX_Size() int {
	return xxx_messageInfo_GetWithdrawResp.Size(m)
}
func (m *GetWithdrawResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWithdrawResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetWithdrawResp proto.InternalMessageInfo

func (m *GetWithdrawResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetWithdrawResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetWithdrawResp) GetLogs() []*GetWithdrawResp_Logs {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *GetWithdrawResp) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type GetWithdrawResp_Logs struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid"`
	Mark                 string   `protobuf:"bytes,2,opt,name=mark,proto3" json:"mark"`
	Tag                  string   `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag"`
	PassedAt             string   `protobuf:"bytes,4,opt,name=passedAt,proto3" json:"passedAt"`
	Confirmations        int32    `protobuf:"varint,5,opt,name=confirmations,proto3" json:"confirmations"`
	TxId                 string   `protobuf:"bytes,6,opt,name=txId,proto3" json:"txId"`
	Status               int32    `protobuf:"varint,7,opt,name=status,proto3" json:"status"`
	Amount               float32  `protobuf:"fixed32,8,opt,name=amount,proto3" json:"amount"`
	UserId               int32    `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id"`
	SourceAddress        string   `protobuf:"bytes,10,opt,name=sourceAddress,proto3" json:"sourceAddress"`
	Address              string   `protobuf:"bytes,11,opt,name=address,proto3" json:"address"`
	Nonce                string   `protobuf:"bytes,12,opt,name=nonce,proto3" json:"nonce"`
	Fee                  float32  `protobuf:"fixed32,13,opt,name=fee,proto3" json:"fee"`
	NetworkFee           float32  `protobuf:"fixed32,14,opt,name=network_fee,json=networkFee,proto3" json:"network_fee"`
	Currency             string   `protobuf:"bytes,15,opt,name=currency,proto3" json:"currency"`
	CreatedAt            string   `protobuf:"bytes,16,opt,name=createdAt,proto3" json:"createdAt"`
	UpdatedAt            string   `protobuf:"bytes,17,opt,name=updatedAt,proto3" json:"updatedAt"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetWithdrawResp_Logs) Reset()         { *m = GetWithdrawResp_Logs{} }
func (m *GetWithdrawResp_Logs) String() string { return proto.CompactTextString(m) }
func (*GetWithdrawResp_Logs) ProtoMessage()    {}
func (*GetWithdrawResp_Logs) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1097521bfd08498, []int{3, 0}
}

func (m *GetWithdrawResp_Logs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetWithdrawResp_Logs.Unmarshal(m, b)
}
func (m *GetWithdrawResp_Logs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetWithdrawResp_Logs.Marshal(b, m, deterministic)
}
func (m *GetWithdrawResp_Logs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetWithdrawResp_Logs.Merge(m, src)
}
func (m *GetWithdrawResp_Logs) XXX_Size() int {
	return xxx_messageInfo_GetWithdrawResp_Logs.Size(m)
}
func (m *GetWithdrawResp_Logs) XXX_DiscardUnknown() {
	xxx_messageInfo_GetWithdrawResp_Logs.DiscardUnknown(m)
}

var xxx_messageInfo_GetWithdrawResp_Logs proto.InternalMessageInfo

func (m *GetWithdrawResp_Logs) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *GetWithdrawResp_Logs) GetMark() string {
	if m != nil {
		return m.Mark
	}
	return ""
}

func (m *GetWithdrawResp_Logs) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

func (m *GetWithdrawResp_Logs) GetPassedAt() string {
	if m != nil {
		return m.PassedAt
	}
	return ""
}

func (m *GetWithdrawResp_Logs) GetConfirmations() int32 {
	if m != nil {
		return m.Confirmations
	}
	return 0
}

func (m *GetWithdrawResp_Logs) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *GetWithdrawResp_Logs) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetWithdrawResp_Logs) GetAmount() float32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *GetWithdrawResp_Logs) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *GetWithdrawResp_Logs) GetSourceAddress() string {
	if m != nil {
		return m.SourceAddress
	}
	return ""
}

func (m *GetWithdrawResp_Logs) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *GetWithdrawResp_Logs) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *GetWithdrawResp_Logs) GetFee() float32 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *GetWithdrawResp_Logs) GetNetworkFee() float32 {
	if m != nil {
		return m.NetworkFee
	}
	return 0
}

func (m *GetWithdrawResp_Logs) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *GetWithdrawResp_Logs) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *GetWithdrawResp_Logs) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*GetWalletReq)(nil), "his_transfer.GetWalletReq")
	proto.RegisterType((*Pagination)(nil), "his_transfer.Pagination")
	proto.RegisterType((*GetDepositResp)(nil), "his_transfer.GetDepositResp")
	proto.RegisterType((*GetDepositResp_Logs)(nil), "his_transfer.GetDepositResp.Logs")
	proto.RegisterType((*GetWithdrawResp)(nil), "his_transfer.GetWithdrawResp")
	proto.RegisterType((*GetWithdrawResp_Logs)(nil), "his_transfer.GetWithdrawResp.Logs")
}

func init() { proto.RegisterFile("proto/his_wallet/his_wallet.proto", fileDescriptor_b1097521bfd08498) }

var fileDescriptor_b1097521bfd08498 = []byte{
	// 717 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0x6e, 0xce, 0xf1, 0xa4, 0xa7, 0x7f, 0xf5, 0xab, 0xbf, 0x15, 0xf5, 0x87, 0x34, 0xe2, 0x22,
	0x17, 0x90, 0x48, 0x45, 0x20, 0x6e, 0x4b, 0x11, 0x6d, 0xc5, 0xa9, 0x5a, 0x90, 0x90, 0xb8, 0xa9,
	0xb6, 0xf6, 0xd6, 0xb1, 0x1a, 0x7b, 0xc3, 0xee, 0x5a, 0x2d, 0xbc, 0x07, 0xaf, 0x00, 0x6f, 0xc0,
	0x35, 0x12, 0x2f, 0xc4, 0x23, 0xa0, 0x19, 0x6f, 0x52, 0xbb, 0x87, 0x48, 0xa8, 0xdc, 0xcd, 0x7c,
	0xdf, 0x7a, 0x76, 0xf6, 0x9b, 0x6f, 0xd7, 0xb0, 0x35, 0xd5, 0xca, 0xaa, 0xd1, 0x38, 0x36, 0x47,
	0x67, 0x62, 0x32, 0x91, 0xb6, 0x10, 0x0e, 0x89, 0x63, 0xcb, 0x88, 0x58, 0x2d, 0x52, 0x73, 0x22,
	0x75, 0xff, 0x7b, 0x05, 0x96, 0xf7, 0xa4, 0x7d, 0x4f, 0x2b, 0xb8, 0xfc, 0xc8, 0x18, 0xd4, 0xb3,
	0x2c, 0x0e, 0xfd, 0x4a, 0xaf, 0x32, 0xf0, 0x38, 0xc5, 0xac, 0x0b, 0xed, 0x20, 0xd3, 0x5a, 0xa6,
	0xc1, 0x27, 0xbf, 0x4a, 0xf8, 0x3c, 0x67, 0x1b, 0xd0, 0x34, 0x56, 0xd8, 0xcc, 0xf8, 0x35, 0x62,
	0x5c, 0xc6, 0x36, 0xc1, 0x33, 0x56, 0x68, 0xfb, 0x2e, 0x4e, 0xa4, 0x5f, 0x27, 0xea, 0x02, 0x60,
	0x3e, 0xb4, 0x64, 0x1a, 0x12, 0xd7, 0x20, 0x6e, 0x96, 0xe2, 0xfe, 0x53, 0x11, 0x49, 0xbf, 0xd9,
	0xab, 0x0c, 0x1a, 0x9c, 0x62, 0xc4, 0x4c, 0xfc, 0x59, 0xfa, 0xad, 0x1c, 0xc3, 0xb8, 0xff, 0xb5,
	0x02, 0x70, 0x28, 0xa2, 0x38, 0x15, 0x36, 0x56, 0x29, 0xeb, 0x41, 0xc7, 0x2a, 0x2b, 0x26, 0x5c,
	0x06, 0x4a, 0xe7, 0xdd, 0x37, 0x78, 0x11, 0xc2, 0x15, 0x79, 0xd3, 0xf6, 0x10, 0xeb, 0x57, 0xf3,
	0x15, 0x05, 0x08, 0x8f, 0x89, 0xdb, 0xbd, 0xc5, 0xad, 0x6a, 0x44, 0xcf, 0x73, 0x76, 0x07, 0x80,
	0x8a, 0xe1, 0x42, 0x43, 0xe7, 0x69, 0xf0, 0x02, 0x82, 0x07, 0x1a, 0x0b, 0xf3, 0x5a, 0x9e, 0x5b,
	0x3a, 0x50, 0x9b, 0xcf, 0xd2, 0xfe, 0xcf, 0x3a, 0xac, 0xee, 0x49, 0xfb, 0x4c, 0x4e, 0x95, 0x89,
	0x2d, 0x97, 0x66, 0x5a, 0xd0, 0x2c, 0xef, 0x73, 0xa6, 0xd9, 0x3a, 0xd4, 0x12, 0x13, 0x39, 0x89,
	0x31, 0x64, 0x8f, 0xa0, 0x3e, 0x51, 0x11, 0x6a, 0x5b, 0x1b, 0x74, 0xb6, 0xb7, 0x86, 0xc5, 0xd9,
	0x0d, 0xcb, 0x55, 0x87, 0x2f, 0x55, 0x64, 0x38, 0x2d, 0x67, 0x4f, 0x00, 0xa6, 0x73, 0x6d, 0xa8,
	0xdb, 0xce, 0xb6, 0x5f, 0xfe, 0xf8, 0x42, 0x3b, 0x5e, 0x58, 0xdb, 0xfd, 0x52, 0x83, 0x3a, 0x16,
	0xba, 0xd6, 0x07, 0x0c, 0xea, 0x89, 0xd0, 0xa7, 0xae, 0x41, 0x8a, 0xb1, 0x67, 0x2b, 0x22, 0x37,
	0x7c, 0x0c, 0x51, 0x68, 0x95, 0xd9, 0x69, 0x66, 0x0f, 0xd2, 0x50, 0x9e, 0x3b, 0xad, 0x8a, 0x10,
	0xbb, 0x07, 0x2b, 0x81, 0x4a, 0x4f, 0x62, 0x9d, 0xd0, 0xa6, 0x86, 0x24, 0x6b, 0xf0, 0x32, 0x88,
	0xbb, 0xd9, 0xf3, 0x83, 0x90, 0x9c, 0xe0, 0x71, 0x8a, 0x51, 0xb9, 0xb1, 0x8c, 0xa3, 0xb1, 0x25,
	0x2f, 0x78, 0xdc, 0x65, 0x28, 0xbf, 0x08, 0x43, 0x2d, 0x8d, 0xf1, 0xdb, 0xb9, 0x9f, 0x5c, 0x8a,
	0x7b, 0x19, 0x95, 0xe9, 0x40, 0xee, 0x38, 0xde, 0x23, 0xbe, 0x0c, 0x16, 0x26, 0x02, 0xa5, 0x89,
	0x6c, 0x40, 0x53, 0x24, 0x2a, 0x4b, 0xad, 0xdf, 0xe9, 0x55, 0x06, 0x55, 0xee, 0x32, 0xf6, 0x1f,
	0xb4, 0x32, 0x23, 0xf5, 0x51, 0x1c, 0xfa, 0xcb, 0xf9, 0x07, 0x98, 0x1e, 0x94, 0xaf, 0xca, 0xca,
	0xa5, 0xab, 0xb2, 0x09, 0x5e, 0xa0, 0xa5, 0xb0, 0x32, 0xdc, 0xb1, 0xfe, 0x6a, 0x7e, 0x25, 0xe6,
	0x00, 0xb2, 0xd9, 0x34, 0x74, 0xec, 0x5a, 0xce, 0xce, 0x81, 0xfe, 0xaf, 0x3a, 0xac, 0xe1, 0x3d,
	0x8d, 0xed, 0x38, 0xd4, 0xe2, 0xec, 0x0f, 0x6d, 0xf4, 0xb8, 0x64, 0xa3, 0xfe, 0x15, 0x1b, 0x15,
	0xcb, 0xfe, 0x1d, 0x1f, 0xfd, 0xb8, 0xbd, 0x8f, 0xe8, 0x3a, 0x1a, 0x43, 0x7a, 0xe4, 0x0f, 0xc8,
	0x3c, 0xbf, 0x9d, 0x83, 0x9c, 0x68, 0xad, 0x1b, 0x26, 0xdd, 0xbe, 0x69, 0xd2, 0x5e, 0x69, 0xd2,
	0x57, 0x8c, 0x05, 0xd7, 0x19, 0xab, 0x60, 0xcc, 0x4e, 0xd9, 0x98, 0xff, 0x42, 0x23, 0x55, 0x69,
	0x20, 0xc9, 0x40, 0x1e, 0xcf, 0x13, 0x94, 0xe1, 0x44, 0x4a, 0xb2, 0x4e, 0x95, 0x63, 0xc8, 0xee,
	0x42, 0x27, 0x95, 0xf6, 0x4c, 0xe9, 0xd3, 0x23, 0x64, 0x56, 0x89, 0x01, 0x07, 0x3d, 0x97, 0xb2,
	0x64, 0xb9, 0xb5, 0x45, 0x96, 0x5b, 0x5f, 0x68, 0xb9, 0x7f, 0x2e, 0x59, 0x6e, 0xfb, 0x5b, 0x05,
	0xbc, 0xfd, 0xd8, 0xe4, 0xbf, 0x06, 0xf6, 0x02, 0x56, 0xf6, 0xa4, 0xdd, 0x8f, 0x8d, 0x7b, 0x72,
	0x58, 0xf7, 0xaa, 0x8b, 0x66, 0x3f, 0x91, 0xee, 0xe6, 0xa2, 0x87, 0xaa, 0xbf, 0xc4, 0x5e, 0xd1,
	0x93, 0x88, 0xc5, 0x9d, 0xf1, 0x16, 0x56, 0xfb, 0x7f, 0xa1, 0x5f, 0xfb, 0x4b, 0x4f, 0x87, 0x1f,
	0xee, 0x47, 0xb1, 0x1d, 0x67, 0xc7, 0xc3, 0x40, 0x25, 0xa3, 0x5d, 0xfe, 0x86, 0xef, 0xf2, 0x51,
	0xa0, 0x1f, 0x04, 0x2a, 0x49, 0x54, 0x3a, 0xba, 0xfc, 0x4f, 0x3c, 0x6e, 0x12, 0xf2, 0xf0, 0x77,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x48, 0x2b, 0x58, 0x71, 0x2e, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HisWalletClient is the client API for HisWallet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HisWalletClient interface {
	GetHisDeposit(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetDepositResp, error)
	GetHisWithdraw(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetWithdrawResp, error)
}

type hisWalletClient struct {
	cc *grpc.ClientConn
}

func NewHisWalletClient(cc *grpc.ClientConn) HisWalletClient {
	return &hisWalletClient{cc}
}

func (c *hisWalletClient) GetHisDeposit(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetDepositResp, error) {
	out := new(GetDepositResp)
	err := c.cc.Invoke(ctx, "/his_transfer.HisWallet/GetHisDeposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hisWalletClient) GetHisWithdraw(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetWithdrawResp, error) {
	out := new(GetWithdrawResp)
	err := c.cc.Invoke(ctx, "/his_transfer.HisWallet/GetHisWithdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HisWalletServer is the server API for HisWallet service.
type HisWalletServer interface {
	GetHisDeposit(context.Context, *GetWalletReq) (*GetDepositResp, error)
	GetHisWithdraw(context.Context, *GetWalletReq) (*GetWithdrawResp, error)
}

// UnimplementedHisWalletServer can be embedded to have forward compatible implementations.
type UnimplementedHisWalletServer struct {
}

func (*UnimplementedHisWalletServer) GetHisDeposit(ctx context.Context, req *GetWalletReq) (*GetDepositResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHisDeposit not implemented")
}
func (*UnimplementedHisWalletServer) GetHisWithdraw(ctx context.Context, req *GetWalletReq) (*GetWithdrawResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHisWithdraw not implemented")
}

func RegisterHisWalletServer(s *grpc.Server, srv HisWalletServer) {
	s.RegisterService(&_HisWallet_serviceDesc, srv)
}

func _HisWallet_GetHisDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HisWalletServer).GetHisDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/his_transfer.HisWallet/GetHisDeposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HisWalletServer).GetHisDeposit(ctx, req.(*GetWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _HisWallet_GetHisWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HisWalletServer).GetHisWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/his_transfer.HisWallet/GetHisWithdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HisWalletServer).GetHisWithdraw(ctx, req.(*GetWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _HisWallet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "his_transfer.HisWallet",
	HandlerType: (*HisWalletServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHisDeposit",
			Handler:    _HisWallet_GetHisDeposit_Handler,
		},
		{
			MethodName: "GetHisWithdraw",
			Handler:    _HisWallet_GetHisWithdraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/his_wallet/his_wallet.proto",
}
